import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface TranslationParameters {
  [key: string]: string | number;
}

const translations = {
  en: {
    // Navigation
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.adPlatform': 'AdPlatform',
    'nav.platforms': 'Platforms',
    'nav.platforms.description': 'TV, Radio, Print & Social',
    'nav.howItWorks': 'How it Works',
    'nav.howItWorks.description': 'Simple 4-step process',
    'nav.programs': 'Programs',
    'nav.programs.description': 'Featured ad slots',
    'nav.analytics': 'Analytics',
    'nav.analytics.description': 'Performance insights',
    'nav.pricing': 'Pricing',
    'nav.pricing.description': 'Transparent pricing',
    'nav.contact': 'Contact',
    'nav.contact.description': 'Get in touch',
    
    // Hero Section
    'hero.title': 'Advertise Anywhere, Anytime',
    'hero.subtitle': 'TV, Radio, Print & Social Media in One Platform',
    'hero.getStarted': 'Get Started',
    'hero.bookSlot': 'Book Your Ad Slot',
    'hero.alt': 'Dubai Media Advertising Platform Hero',
    
    // CTA Section
    'cta.title': 'Ready to Transform Your Advertising?',
    'cta.subtitle': 'Join thousands of businesses already using our platform to reach more customers and achieve better results across all media channels.',
    'cta.bookDemo': 'Book a Free Demo',
    'cta.createCampaign': 'Create Your Campaign',
    'cta.support.title': '24/7 Support',
    'cta.support.description': 'Get help whenever you need it',
    'cta.setup.title': 'Quick Setup',
    'cta.setup.description': 'Launch campaigns in minutes',
    'cta.results.title': 'Proven Results',
    'cta.results.description': 'Average 200% ROI improvement',
    
    // Contact Section
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Have questions about our platform? Our team of advertising experts is here to help you create successful campaigns across all media channels.',
    'contact.liveChat': 'Live Chat',
    'contact.liveChat.description': 'Get instant help from our support team',
    'contact.startChat': 'Start Chat',
    'contact.callUs': 'Call Us',
    'contact.callUs.description': 'Speak with an advertising specialist',
    'contact.emailSupport': 'Email Support',
    'contact.emailSupport.description': 'Send us your questions',
    'contact.sendMessage': 'Send us a message',
    'contact.chatNow': 'Chat Now',
    'contact.phone': '1-800-ADS-HELP',
    'contact.phone.hours': 'Mon-Fri: 9AM-6PM EST',
    'contact.email': 'support@adplatform.com',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.email_label': 'Email',
    'contact.company': 'Company',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.firstName.placeholder': 'John',
    'contact.lastName.placeholder': 'Doe',
    'contact.email.placeholder': 'john@company.com',
    'contact.company.placeholder': 'Company Name',
    'contact.subject.placeholder': 'How can we help you?',
    'contact.message.placeholder': 'Tell us about your advertising needs...',
    'contact.submit': 'Send Message',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'How quickly can I launch a campaign?',
    'contact.faq.a1': 'Most campaigns can be launched within 24-48 hours after content approval and payment confirmation.',
    'contact.faq.q2': 'What platforms do you support?',
    'contact.faq.a2': 'We support television, radio, print media, and all major social media platforms including Facebook, Instagram, Twitter, and LinkedIn.',
    'contact.faq.q3': 'Can I track campaign performance?',
    'contact.faq.a3': 'Yes! Our analytics dashboard provides real-time tracking of reach, engagement, conversions, and ROI across all platforms.',
    'contact.faq.q4': 'Is there a minimum budget requirement?',
    'contact.faq.a4': 'Minimum budgets vary by platform. Social media campaigns can start from $500, while TV and radio have higher minimums based on market size.',
    
    // Platform Selection
    'platform.title': 'Choose Your Platform',
    'platform.tv': 'Television',
    'platform.radio': 'Radio',
    'platform.print': 'Print Media',
    'platform.social': 'Social Media',
    
    // Footer
    'footer.brand': 'DubaiTV',
    'footer.description': 'The all-in-one advertising platform that connects your brand with audiences across television, radio, print, and social media channels.',
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.platform.title': 'Platform',
    'footer.platform.howItWorks': 'How It Works',
    'footer.platform.pricing': 'Pricing',
    'footer.platform.programs': 'Featured Programs',
    'footer.platform.analytics': 'Analytics',
    'footer.support.title': 'Support',
    'footer.support.help': 'Help Center',
    'footer.support.contact': 'Contact Us',
    'footer.support.chat': 'Live Chat',
    'footer.support.docs': 'Documentation',
    'footer.company.title': 'Company',
    'footer.company.about': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.press': 'Press',
    'footer.company.blog': 'Blog',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.compliance': 'Compliance',
    'footer.followUs': 'Follow us:',
    'footer.copyright': '© 2024 DubaiTV. All rights reserved.',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Get your advertising campaign up and running in just four simple steps. Our streamlined process makes it easy to reach your audience across any platform.',
    'howItWorks.step1.title': 'Select Platform',
    'howItWorks.step1.description': 'Choose from TV, Radio, Print, or Social Media based on your campaign goals',
    'howItWorks.step2.title': 'Pick Program / Time Slot',
    'howItWorks.step2.description': 'Browse available programs and time slots that match your target audience',
    'howItWorks.step3.title': 'Upload Ad Content',
    'howItWorks.step3.description': 'Upload your creative assets or use our templates to create compelling ads',
    'howItWorks.step4.title': 'Confirm & Pay',
    'howItWorks.step4.description': 'Review your campaign details and make secure payment to launch your ads',
    
    // Featured Programs
    'featured.title': 'Featured Programs & Slots',
    'featured.subtitle': 'Discover our most popular advertising opportunities across all platforms. These premium slots offer the best value and audience engagement.',
    'featured.primeTime': 'Prime Time',
    'featured.views': 'views',
    'featured.rating': 'rating',
    'featured.starting': 'Starting from',
    'featured.bookSlot': 'Book This Slot',
    'featured.viewAllSlots': 'View All Available Slots',
    'featured.viewers': 'viewers',
    'featured.listeners': 'listeners',
    'featured.readers': 'readers',
    'featured.reach': 'reach',
    
    // Program Names
    'programs.morningNews': 'Morning News Show',
    'programs.driveTime': 'Drive Time Radio',
    'programs.weekendSports': 'Weekend Sports Special',
    'programs.businessWeekly': 'Business Weekly',
    'programs.eveningEntertainment': 'Evening Entertainment',
    'programs.socialCampaign': 'Social Campaign Package',
    
    // Time Slots
    'timeSlots.morning': '7:00 - 9:00 AM',
    'timeSlots.evening': '5:00 - 7:00 PM',
    'timeSlots.afternoon': 'Saturday 2:00 PM',
    'timeSlots.monday': 'Monday Edition',
    'timeSlots.primeTime': '8:00 - 10:00 PM',
    'timeSlots.weekCampaign': '7-day campaign',
    
    // Platforms
    'platforms.television': 'Television',
    'platforms.radio': 'Radio',
    'platforms.print': 'Print',
    'platforms.socialMedia': 'Social Media',
    
    // Categories
    'categories.news': 'News',
    'categories.talk': 'Talk',
    'categories.sports': 'Sports',
    'categories.business': 'Business',
    'categories.entertainment': 'Entertainment',
    'categories.digital': 'Digital',
    
    // Analytics
    'analytics.title': 'Audience Reach & Analytics',
    'analytics.subtitle': 'Get detailed insights into your campaign performance with real-time analytics. Track reach, engagement, and ROI across all platforms.',
    'analytics.totalReach': 'Total Reach',
    'analytics.avgEngagement': 'Avg. Engagement',
    'analytics.conversionRate': 'Conversion Rate',
    'analytics.roi': 'ROI',
    'analytics.fromLastMonth': 'from last month',
    'analytics.reachByPlatform': 'Reach by Platform',
    'analytics.engagementRates': 'Engagement Rates',
    'analytics.audienceDemographics': 'Audience Demographics',
    'analytics.ageGroups': 'Age Groups',
    'analytics.gender': 'Gender',
    'analytics.location': 'Location',
    'analytics.platform.tv': 'TV',
    'analytics.platform.radio': 'Radio',
    'analytics.platform.print': 'Print',
    'analytics.platform.social': 'Social',
    'analytics.age.18-24': '18-24',
    'analytics.age.25-34': '25-34',
    'analytics.age.35-44': '35-44',
    'analytics.age.45+': '45+',
    'analytics.gender.male': 'Male',
    'analytics.gender.female': 'Female',
    'analytics.location.urban': 'Urban',
    'analytics.location.suburban': 'Suburban',
    'analytics.location.rural': 'Rural',
    
    // Testimonials
    'testimonials.title': 'Success Stories',
    'testimonials.subtitle': 'See how businesses like yours have achieved remarkable results with our multi-platform advertising solution.',
    
    // Testimonial 1 - Sarah Johnson
    'testimonials.sarah.name': 'Sarah Johnson',
    'testimonials.sarah.company': 'TechStart Inc.',
    'testimonials.sarah.role': 'Marketing Director',
    'testimonials.sarah.content': 'The unified platform saved us 40% on our advertising budget while increasing our reach by 200%. The analytics dashboard gives us insights we never had before.',
    'testimonials.sarah.campaign': 'Multi-platform launch',
    'testimonials.sarah.results': '+200% reach, 40% cost savings',
    
    // Testimonial 2 - Michael Chen
    'testimonials.michael.name': 'Michael Chen',
    'testimonials.michael.company': 'RetailMax',
    'testimonials.michael.role': 'Brand Manager',
    'testimonials.michael.content': 'Managing campaigns across TV, radio, and social media used to be a nightmare. This platform made it seamless and our ROI improved by 150%.',
    'testimonials.michael.campaign': 'Holiday season campaign',
    'testimonials.michael.results': '+150% ROI, 3.2M impressions',
    
    // Testimonial 3 - Emily Rodriguez
    'testimonials.emily.name': 'Emily Rodriguez',
    'testimonials.emily.company': 'LocalEats',
    'testimonials.emily.role': 'Owner',
    'testimonials.emily.content': 'As a small business, I thought multi-platform advertising was out of reach. This platform made it affordable and effective. Sales increased 85% in the first quarter.',
    'testimonials.emily.campaign': 'Local awareness campaign',
    'testimonials.emily.results': '+85% sales growth',
    
    // Testimonial 4 - David Thompson
    'testimonials.david.name': 'David Thompson',
    'testimonials.david.company': 'FitLife Gyms',
    'testimonials.david.role': 'Marketing Head',
    'testimonials.david.content': 'The targeting capabilities are incredible. We reached exactly the right audience across all channels and saw a 300% increase in gym memberships.',
    'testimonials.david.campaign': 'Fitness challenge promotion',
    'testimonials.david.results': '+300% memberships',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back! Here\'s what\'s happening with your campaigns.',
    'dashboard.mediaIntelligence': 'Media Intelligence',
    'dashboard.user': 'John Doe',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    'dashboard.logout': 'Logout',
    'dashboard.overview': 'Overview',
    'dashboard.newBooking': 'New Booking',
    'dashboard.myBookings': 'My Bookings',
    'dashboard.myBookings.description': 'Your booking history will appear here',
    'dashboard.packages': 'Available Packages',
    'dashboard.packages.description': 'Special advertising packages and deals',
    'dashboard.invoices': 'Invoices',
    'dashboard.invoices.description': 'Your billing history and invoices',
    'dashboard.analytics': 'Analytics',
    'dashboard.support': 'Support',
    
    // Dashboard Stats
    'stats.totalCampaigns': 'Total Campaigns',
    'stats.activeAds': 'Active Ads',
    'stats.totalReach': 'Total Reach',
    'stats.monthlySpend': 'Monthly Spend',
    'stats.fromLastMonth': 'from last month',
    
    // Booking Status
    'status.confirmed': 'Confirmed',
    'status.creativeReview': 'Creative Review',
    'status.paymentDue': 'Payment Due',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    
    // Media Selection
    'mediaSelection.title': 'Select Your Media Outlet',
    'mediaSelection.subtitle': 'Choose from our premium media partners',
    'mediaSelection.search': 'Search media outlets...',
    'mediaSelection.all': 'All',
    'mediaSelection.tv': 'TV',
    'mediaSelection.radio': 'Radio',
    'mediaSelection.print': 'Print',
    'mediaSelection.digital': 'Digital',
    'mediaSelection.reach': 'Reach:',
    'mediaSelection.select': 'Select',
    'mediaSelection.selected': 'Selected:',
    'mediaSelection.noResults': 'No outlets found',
    'mediaSelection.noResults.description': 'Try adjusting your search or filter criteria',
    'mediaSelection.continue': 'Continue',
    'mediaSelection.back': 'Back',
    'mediaSelection.step': 'Step',
    'mediaSelection.of': 'of',
    'mediaSelection.allMedia': 'All Media',
    'mediaSelection.tvChannels': 'TV Channels',
    'mediaSelection.radioStations': 'Radio',
    'mediaSelection.printMedia': 'Print',
    'mediaSelection.digitalPlatforms': 'Digital',
    'mediaSelection.premium': 'Premium',
    
    // Media Outlet Descriptions
    'media.dubaiTV.desc': 'Premier Arabic entertainment channel',
    'media.samaDubai.desc': 'Dubai\'s lifestyle and culture channel',
    'media.dubaiSports.desc': 'Sports and live events',
    'media.dubaiOne.desc': 'English language channel',
    'media.noorDubai.desc': 'Islamic and cultural programming',
    'media.dubaiFM.desc': 'Music and entertainment',
    'media.dubaiEye.desc': 'Talk radio and news',
    'media.alBayan.desc': 'Arabic daily newspaper',
    'media.emiratesToday.desc': 'English business daily',
    'media.gulfNews.desc': 'Leading English daily',
    'media.dubaiPortal.desc': 'Official Dubai government portal',
    'media.dubaiTourism.desc': 'Tourism and travel platform',
    'media.socialBundle.desc': 'Instagram, Facebook, Twitter',
    'media.viewers': 'viewers',
    'media.listeners': 'listeners',
    'media.readers': 'readers',
    'media.visitors': 'visitors',
    'media.users': 'users',
    'media.impressions': 'impressions',
    
    // Media Outlet Names
    'media.dubaiTV.name': 'Dubai TV',
    'media.samaDubai.name': 'Sama Dubai', 
    'media.dubaiSports.name': 'Dubai Sports',
    'media.dubaiOne.name': 'Dubai One',
    'media.noorDubai.name': 'Noor Dubai',
    'media.dubaiFM.name': 'Dubai FM',
    'media.dubaiEye.name': 'Dubai Eye',
    'media.alBayan.name': 'Al Bayan',
    'media.emiratesToday.name': 'Emirates Today',
    'media.gulfNews.name': 'Gulf News',
    'media.dubaiPortal.name': 'Dubai.ae Portal',
    'media.dubaiTourism.name': 'Dubai Tourism App',
    'media.socialBundle.name': 'Social Media Bundle',
    
    // Media Types
    'media.type.tv': 'TV',
    'media.type.radio': 'RADIO',
    'media.type.print': 'PRINT',
    'media.type.digital': 'DIGITAL',
    
    // Program Names and Details
    'program.morningDubai.name': 'Morning Dubai',
    'program.morningDubai.category': 'News & Current Affairs',
    'program.cityPulse.name': 'City Pulse',
    'program.cityPulse.category': 'Lifestyle',
    'program.primeTimeNews.name': 'Prime Time News',
    'program.primeTimeNews.category': 'News',
    'program.businessToday.name': 'Business Today',
    'program.businessToday.category': 'Business',
    'program.hours': 'hours',
    'program.hour': 'hour',
    'program.minutes': 'minutes',
    'program.viewers': 'viewers',
    'program.adults': 'Adults',
    'program.professionals': 'Professionals',
    
    // Pricing & Packages
    'pricing.title': 'Pricing & Packages',
    'pricing.subtitle': 'Customize your booking with add-ons and packages',
    'pricing.step': 'Step 3 of 6',
    'pricing.back': 'Back',
    'pricing.basePricing': 'Base Pricing',
    'pricing.basePrice': 'Base Price',
    'pricing.at': 'at',
    'pricing.enhanceCampaign': 'Enhance Your Campaign',
    'pricing.seasonalPackages': 'Seasonal Packages',
    'pricing.pricingSummary': 'Pricing Summary',
    'pricing.totalPrice': 'Total Price',
    'pricing.youSave': 'You Save',
    'pricing.discount': 'Discount',
    'pricing.continueToMaterial': 'Continue to Ad Material',
    'pricing.proTip': 'Pro Tip:',
    'pricing.proTipText': 'Seasonal packages offer the best value and include additional benefits like priority approval and enhanced analytics.',
    
    // Add-ons
    'addons.peakHour.name': 'Peak Hour Boost',
    'addons.peakHour.desc': 'Enhanced visibility during prime time',
    'addons.weekend.name': 'Weekend Premium', 
    'addons.weekend.desc': 'Additional weekend slots',
    'addons.multiSlot.name': 'Multi-Slot Discount',
    'addons.multiSlot.desc': '10% off when booking 3+ slots',
    'addons.analytics.name': 'Audience Analytics',
    'addons.analytics.desc': 'Detailed viewership reports',
    
    // Seasonal Packages
    'packages.ramadan.name': 'Ramadan Special Bundle',
    'packages.ramadan.desc': 'Perfect for Ramadan campaigns with premium slots',
    'packages.ramadan.feature1': '5 Premium Time Slots',
    'packages.ramadan.feature2': 'Iftar & Suhoor Timing',
    'packages.ramadan.feature3': 'Custom Ramadan Creative',
    'packages.ramadan.feature4': 'Enhanced Analytics',
    'packages.ramadan.feature5': 'Priority Approval',
    'packages.ramadan.badge': 'Most Popular',
    
    'packages.fifa.name': 'FIFA World Cup Package',
    'packages.fifa.desc': 'Sports-focused advertising during major events',
    'packages.fifa.feature1': '8 Sports Channel Slots',
    'packages.fifa.feature2': 'Match Day Priority',
    'packages.fifa.feature3': 'Sports Creative Templates',
    'packages.fifa.feature4': 'Real-time Performance',
    'packages.fifa.feature5': 'Social Media Cross-promotion',
    'packages.fifa.badge': 'Limited Time',
    
    'packages.eid.name': 'Eid Celebration Special',
    'packages.eid.desc': 'Festive campaigns for Eid celebrations',
    'packages.eid.feature1': '4 Prime Time Slots',
    'packages.eid.feature2': 'Eid Creative Suite',
    'packages.eid.feature3': 'Multi-language Support',
    'packages.eid.feature4': 'Festival Analytics',
    'packages.eid.feature5': 'Express Approval',
    'packages.eid.badge': 'New',
    
    // Program Time Slot
    'programTime.title': 'Select Program & Time Slot',
    'programTime.subtitle': 'Choose your preferred timing',
    'programTime.selectedDate': 'Selected Date',
    'programTime.selectedDates': 'Selected Dates',
    'programTime.to': 'to',
    'programTime.availablePrograms': 'Available Programs',
    'programTime.availableTimeSlots': 'Available Time Slots',
    'programTime.booked': 'Booked',
    'programTime.selectProgram': 'Please select a program first',
    'programTime.selectTimeSlot': 'Please select a time slot',
    'programTime.back': 'Back',
    'programTime.continue': 'Continue to Pricing',
    'programTime.step2of6': 'Step 2 of 6',
    'programTime.available': 'Available',
    'programTime.selectDate': 'Select Date',
    'programTime.days': 'days',
    'programTime.premium': 'Premium',
    'programTime.morning': 'Morning',
    'programTime.afternoon': 'Afternoon',
    'programTime.evening': 'Evening',
    'programTime.late': 'Late Night',
    'programTime.timeSlotLabel': 'Time Slot',
    'programTime.hour': 'hour',
    'programTime.programs': 'Programs',
    'programTime.timeSlots': 'Time Slots',
    'programTime.target': 'Target',
    'programTime.day': 'day',
    'programTime.selected': 'Selected',
    'programTime.at': 'at',
    'programTime.basePrice': 'Base Price',
    'programTime.total': 'Total',
    
    // Payment
    'payment.title': 'Payment & Checkout',
    'payment.subtitle': 'Complete your booking securely',
    'payment.step': 'Step 6 of 6',
    'payment.back': 'Back',
    'payment.method': 'Payment Method',
    'payment.creditCard': 'Credit / Debit Card',
    'payment.creditCardDesc': 'Visa, Mastercard, American Express',
    'payment.instant': 'Instant',
    'payment.bankTransfer': 'Bank Transfer',
    'payment.bankTransferDesc': 'Direct bank to bank transfer',
    'payment.days1to2': '1-2 Days',
    'payment.digitalWallet': 'Digital Wallet',
    'payment.digitalWalletDesc': 'Apple Pay, Google Pay, Samsung Pay',
    'payment.cardDetails': 'Card Details',
    'payment.cardNumber': 'Card Number',
    'payment.expiryDate': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.cardholderName': 'Cardholder Name',
    'payment.cardNamePlaceholder': 'Name as it appears on card',
    'payment.bankTransferDetails': 'Bank Transfer Details',
    'payment.transferTo': 'Transfer to:',
    'payment.bank': 'Bank',
    'payment.accountName': 'Account Name',
    'payment.accountNumber': 'Account Number',
    'payment.swiftCode': 'SWIFT Code',
    'payment.iban': 'IBAN',
    'payment.referenceNumber': 'Reference Number',
    'payment.referenceNote': 'Please include this reference number with your transfer',
    'payment.digitalWalletSelect': 'Select your preferred digital wallet to complete the payment.',
    'payment.applePay': 'Apple Pay',
    'payment.googlePay': 'Google Pay',
    'payment.samsungPay': 'Samsung Pay',
    'payment.securePayment': 'Secure Payment',
    'payment.securePaymentDesc': 'Your payment information is encrypted and secure. We use industry-standard SSL encryption and do not store your payment details.',
    'payment.paymentSummary': 'Payment Summary',
    'payment.mediaOutlet': 'Media Outlet',
    'payment.program': 'Program',
    'payment.dateTime': 'Date & Time',
    'payment.subtotal': 'Subtotal',
    'payment.vat': 'VAT (5%)',
    'payment.totalAmount': 'Total Amount',
    'payment.processing': 'Processing...',
    'payment.payButton': 'Pay',
    'payment.bankTransferNote': 'Bank Transfer Note',
    'payment.bankTransferNoteDesc': 'Your booking will be confirmed once payment is received (1-2 business days).',
    'payment.sslEncrypted': '256-bit SSL Encrypted',
    'programTime.daySelected': 'day selected',
    'programTime.daysSelected': 'days selected',
    'programTime.pricingPerDay': 'Pricing will be calculated per day',
    'programTime.noDateSelected': 'No date selected',
    
    // Review & Confirmation
    'pricing.enterprise.description': 'Advanced features for large organizations',
    'pricing.features': 'Features:',
    'pricing.selectPackage': 'Select Package',
    'pricing.mostPopular': 'Most Popular',
    
    // Booking Success
    'success.title': 'Booking Confirmed!',
    'success.subtitle': 'Your advertisement booking has been successfully submitted',
    'success.bookingNumber': 'Booking Number',
    'success.nextSteps': 'What happens next?',
    'success.approval': 'Creative Approval',
    'success.approval.description': 'Our team will review your ad materials',
    'success.scheduling': 'Scheduling',
    'success.scheduling.description': 'Your ad will be scheduled for the selected time slots',
    'success.goLive': 'Go Live',
    'success.goLive.description': 'Your advertisement will start running',
    'success.quickActions': 'Quick Actions',
    'success.downloadInvoice': 'Download Invoice',
    'success.viewBooking': 'View Booking Details',
    'success.newBooking': 'Create New Booking',
    'success.dashboard': 'Back to Dashboard',
    'success.bookingReference': 'Booking Reference:',
    'success.bookingSummary': 'Booking Summary',
    'success.mediaOutlet': 'Media Outlet',
    'success.program': 'Program',
    'success.timeSlot': 'Time Slot',
    
    // Approval Workflow
    'approval.title': 'Creative Approval Process',
    'approval.subtitle': 'Track the status of your ad creative review',
    'approval.currentStatus': 'Current Status',
    'approval.submitted': 'Submitted',
    'approval.submitted.description': 'Your creative materials have been submitted for review',
    'approval.review': 'Under Review',
    'approval.review.description': 'Our team is reviewing your ad content for compliance',
    'approval.approved': 'Approved',
    'approval.approved.description': 'Your ad has been approved and is ready to go live',
    'approval.estimatedTime': 'Estimated completion time',
    'approval.businessDays': 'business days',
    'approval.notes': 'Review Notes',
    'approval.contactSupport': 'Contact Support',
    'approval.uploadRevised': 'Upload Revised Materials',
    'approval.checkStatus': 'Check Status',
    
    // SignUp Forms
    'signup.title': 'Create Your Account',
    'signup.backToHome': 'Back to Home',
    'signup.description': 'Complete the registration process to start advertising across multiple channels',
    'signup.stepOf': 'Step {step} of {total}',
    'signup.percentComplete': '{percent}% Complete',

    // Step Titles
    'signup.steps.basicAccount': 'Basic Account Information',
    'signup.steps.businessDetails': 'Business / Company Details',
    'signup.steps.userRole': 'User Role & Type',
    'signup.steps.accountTypeAddress': 'Account Type & Address Details',
    'signup.steps.addressContact': 'Address & Contact Details',
    'signup.steps.paymentPreferences': 'Payment Preferences',
    'signup.steps.complianceApproval': 'Compliance & Approval',
    'signup.subtitle': 'Join our advertising platform',
    'signup.progress': 'Step {{current}} of {{total}}',
    'signup.next': 'Next',
    'signup.back': 'Back',
    'signup.submit': 'Submit Application',
    'signup.success': 'Registration submitted successfully! Your account is pending review.',
    
    // Basic Account Info
    'signup.basicAccount.firstName': 'First Name',
    'signup.basicAccount.firstNamePlaceholder': 'Enter your first name',
    'signup.basicAccount.lastName': 'Last Name',
    'signup.basicAccount.lastNamePlaceholder': 'Enter your last name',
    'signup.basicAccount.email': 'Email Address',
    'signup.basicAccount.emailPlaceholder': 'your.email@company.com',
    'signup.basicAccount.verify': 'Verify',
    'signup.basicAccount.verified': 'Verified',
    'signup.basicAccount.emailVerified': 'Email verified successfully',
    'signup.basicAccount.mobile': 'Mobile Number',
    'signup.basicAccount.mobilePlaceholder': '+971 50 123 4567',
    'signup.basicAccount.sendOTP': 'Send OTP',
    'signup.basicAccount.mobileVerified': 'Mobile verified successfully',
    'signup.basicAccount.password': 'Password',
    'signup.basicAccount.passwordPlaceholder': 'Create a strong password',
    'signup.basicAccount.confirmPassword': 'Confirm Password',
    'signup.basicAccount.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.basicAccount.passwordStrength.weak': 'Weak',
    'signup.basicAccount.passwordStrength.fair': 'Fair',
    'signup.basicAccount.passwordStrength.good': 'Good',
    'signup.basicAccount.passwordStrength.strong': 'Strong',
    'signup.basicAccount.passwordRequirements.length': 'At least 8 characters',
    'signup.basicAccount.passwordRequirements.uppercase': 'One uppercase letter',
    'signup.basicAccount.passwordRequirements.lowercase': 'One lowercase letter',
    'signup.basicAccount.passwordRequirements.special': 'Numbers and special characters',
    'signup.basicAccount.passwordsMatch': 'Passwords match',
    'signup.basicAccount.passwordsDontMatch': 'Passwords don\'t match',
    'signup.basicAccount.preferredLanguage': 'Preferred Language',
    'signup.basicAccount.languagePlaceholder': 'Select your preferred language',
    'signup.basicAccount.english': 'English',
    'signup.basicAccount.arabic': 'العربية (Arabic)',
    
    // Form Fields
    'form.required': 'Required',
    'form.optional': 'Optional',
    'form.select': 'Select...',
    'form.choose': 'Choose',
    'form.search': 'Search...',
    'form.filter': 'Filter',
    'form.all': 'All',
    'form.none': 'None',
    'form.other': 'Other',
    'form.yes': 'Yes',
    'form.no': 'No',
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'form.continue': 'Continue',
    'form.finish': 'Finish',
    'form.edit': 'Edit',
    'form.delete': 'Delete',
    'form.confirm': 'Confirm',
    'form.close': 'Close',
    
    // General UI
    'ui.loading': 'Loading...',
    'ui.error': 'Error',
    'ui.success': 'Success',
    'ui.warning': 'Warning',
    'ui.info': 'Information',
    'ui.notFound': 'Not Found',
    'ui.noData': 'No Data Available',
    'ui.tryAgain': 'Try Again',
    'ui.refresh': 'Refresh',
    'ui.viewAll': 'View All',
    'ui.showMore': 'Show More',
    'ui.showLess': 'Show Less',
    'ui.readMore': 'Read More',
    'ui.collapse': 'Collapse',
    'ui.expand': 'Expand',
    'ui.download': 'Download',
    'ui.upload': 'Upload',
    'ui.preview': 'Preview',
    'ui.print': 'Print',
    'ui.share': 'Share',
    'ui.copy': 'Copy',
    'ui.cut': 'Cut',
    'ui.paste': 'Paste',
    
    // Platform Selection
    'platforms.title': 'Choose Your Platform',
    'platforms.subtitle': 'Select the media platform that best fits your campaign goals. Each platform offers unique advantages to reach your target audience.',
    'platforms.tv.title': 'Television',
    'platforms.tv.description': 'Reach millions through prime time slots and popular shows',
    'platforms.radio.title': 'Radio',
    'platforms.radio.description': 'Connect with commuters and local audiences',
    'platforms.print.title': 'Print Media',
    'platforms.print.description': 'Target engaged readers with newspaper and magazine ads',
    'platforms.social.title': 'Social Media',
    'platforms.social.description': 'Engage with digital natives across all major platforms',
    
    // Dashboard Home specific
    'dashboard.stats.activeBookings': 'Active Bookings',
    'dashboard.upcomingAds': 'Upcoming Ads',
    'dashboard.upcomingAds.scheduled': 'scheduled',
    'dashboard.upcomingAds.noScheduled': 'No upcoming ads scheduled',
    'dashboard.pendingApprovals': 'Pending Approvals',
    'dashboard.pendingApprovals.pending': 'pending',
    'dashboard.pendingApprovals.allApproved': 'All campaigns approved',
    'dashboard.pendingApprovals.submitted': 'Submitted:',
    'dashboard.paymentsDue': 'Payments Due',
    'dashboard.paymentsDue.overdue': 'overdue',
    'dashboard.paymentsDue.due': 'Due:',
    'dashboard.paymentsDue.payNow': 'Pay Now',
    'dashboard.paymentsDue.allUpToDate': 'All payments up to date',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.quickActions.newBooking': 'New Booking',
    'dashboard.quickActions.viewSchedule': 'View Schedule',
    'dashboard.quickActions.analytics': 'Analytics',
    'dashboard.quickActions.billing': 'Billing',
    'dashboard.createNewBooking': 'Create New Booking',
    'dashboard.backToDashboard': 'Back to Dashboard',
    
    // Review Confirmation
    'review.title': 'Review & Confirm',
    'review.subtitle': 'Please review your booking details before submitting',
    'review.step': 'Step 5 of 6',
    'review.back': 'Back',
    'review.bookingSummary': 'Booking Summary',
    'review.edit': 'Edit',
    'review.programSchedule': 'Program & Schedule',
    'review.program': 'Program',
    'review.category': 'Category',
    'review.date': 'Date',
    'review.timeSlot': 'Time Slot',
    'review.pricingBreakdown': 'Pricing Breakdown',
    'review.basePrice': 'Base Price',
    'review.addOns': 'Add-ons:',
    'review.totalAmount': 'Total Amount',
    'review.adMaterial': 'Advertisement Material',
    'review.uploadedFile': 'Uploaded File',
    'review.yourUploadedAd': 'Your uploaded ad',
    'review.readyForReview': 'Ready for Review',
    'review.customTemplateDesign': 'Custom Template Design',
    'review.company': 'Company',
    'review.message': 'Message',
    'review.toBeCreated': 'To be created',
    'review.importantInfo': 'Important Information',
    'review.reviewTime': '• Your booking will be reviewed within 24-48 hours',
    'review.paymentProcess': '• Payment will be processed after approval',
    'review.changesFees': '• Changes to approved bookings may require additional fees',
    'review.cancellation': '• Bookings must be cancelled at least 72 hours in advance',
    'review.termsConditions': 'Terms & Conditions',
    'review.agreeToTerms': 'I agree to the',
    'review.termsOfService': 'Terms of Service',
    'review.and': 'and',
    'review.adPolicy': 'Media Intelligence Advertising Policy',
    'review.marketingConsent': 'I agree to receive marketing communications and booking updates via email and SMS',
    'review.keyTerms': 'Key Terms Summary:',
    'review.bookingApproval': '• Booking confirmation is subject to creative and legal approval',
    'review.paymentDue': '• Payment is due within 7 days of approval',
    'review.contentCompliance': '• Content must comply with UAE media regulations',
    'review.contentRejection': '• MI reserves the right to reject inappropriate content',
    'review.refundPolicy': '• Refunds are only available for bookings cancelled by MI',
    'review.backToEdit': 'Back to Edit',
    'review.submitForApproval': 'Submit for Approval',
    'review.acceptTermsRequired': 'Please accept the terms and conditions to proceed',
    'review.channel': 'Channel',
    
    // UserRoleType
    'signup.userRoleType.stepRemoved': 'Step Removed',
    'signup.userRoleType.stepRemovedDescription': 'Account type selection has been moved to the next step. Please continue.',
    'signup.userRoleType.stepCompleted': 'Step Completed',
    'signup.userRoleType.stepCompletedDescription': 'This step has been removed. Please continue to the next step.',
    'signup.userRoleType.accountSetup': 'Account Setup',
    'signup.userRoleType.agencyMessage': 'As an agency, you\'ll have access to multi-client management tools and advanced features.',
    'signup.userRoleType.directMessage': 'As a direct advertiser, you\'ll have a streamlined experience focused on your business needs.',

    // ComplianceApproval
    'signup.complianceApproval.approvalProcess': 'Approval Process',
    'signup.complianceApproval.approvalProcessDescription': 'Your application will go through a comprehensive review process to ensure quality and compliance with advertising standards.',
    'signup.complianceApproval.reviewTimeline': 'Review Process Timeline',
    'signup.complianceApproval.creativeReview': 'Creative Review',
    'signup.complianceApproval.creativeReviewDescription': 'Content guidelines and creative standards verification',
    'signup.complianceApproval.legalCompliance': 'Legal Compliance',
    'signup.complianceApproval.legalComplianceDescription': 'Terms compliance and regulatory requirements check',
    'signup.complianceApproval.financialVerification': 'Financial Verification',
    'signup.complianceApproval.financialVerificationDescription': 'Payment setup and credit assessment',
    'signup.complianceApproval.estimatedTime': 'Estimated time:',
    'signup.complianceApproval.estimatedTime1': '1-2 business days',
    'signup.complianceApproval.estimatedTime2': '2-3 business days',
    'signup.complianceApproval.estimatedTime3': '1-2 business days',
    'signup.complianceApproval.afterApproval': 'What happens after approval?',
    'signup.complianceApproval.afterApproval1': 'You\'ll receive an email confirmation with login credentials',
    'signup.complianceApproval.afterApproval2': 'Access to the full advertising platform dashboard',
    'signup.complianceApproval.afterApproval3': 'Ability to create and launch campaigns across all channels',
    'signup.complianceApproval.afterApproval4': 'Dedicated account manager assignment (for agency accounts)',
    'signup.complianceApproval.finalConfirmation': 'Final Confirmation',
    'signup.complianceApproval.infoAccurate': 'I confirm that all information provided is accurate and complete',
    'signup.complianceApproval.infoAccurateNote': 'Providing false information may result in account rejection or termination',
    'signup.complianceApproval.termsAccepted': 'I agree to the Terms & Conditions and Privacy Policy',
    'signup.complianceApproval.termsConditions': 'Terms & Conditions',
    'signup.complianceApproval.privacyPolicy': 'Privacy Policy',
    'signup.complianceApproval.readyToSubmit': 'Ready to submit your application?',
    'signup.complianceApproval.readyToSubmitDescription': 'Once submitted, you\'ll receive a confirmation email and can track your application status through our support portal.',
    'signup.complianceApproval.submitForApproval': 'Submit for Approval',

    // Business Details
    'signup.businessDetails.companyName': 'Company / Agency Name',
    'signup.businessDetails.companyNamePlaceholder': 'Enter your company or agency name',
    'signup.businessDetails.tradeLicenseNumber': 'Trade License Number',
    'signup.businessDetails.tradeLicenseNumberPlaceholder': 'Enter your trade license number',
    'signup.businessDetails.idType': 'ID Type',
    'signup.businessDetails.idTypeNote': 'Choose the type of identification document you will upload',
    'signup.businessDetails.emiratesIdOption': 'Emirates ID',
    'signup.businessDetails.passportOption': 'Passport',
    'signup.businessDetails.visaOption': 'Visa',
    'signup.businessDetails.emiratesId': 'Emirates ID',
    'signup.businessDetails.emiratesIdPlaceholder': 'Enter your Emirates ID number (784-XXXX-XXXXXXX-X)',
    'signup.businessDetails.passportNumber': 'Passport Number',
    'signup.businessDetails.passportNumberPlaceholder': 'Enter your passport number',
    'signup.businessDetails.visaNumber': 'Visa Number',
    'signup.businessDetails.visaNumberPlaceholder': 'Enter your visa number',
    'signup.businessDetails.uploadEmiratesId': 'Upload Emirates ID',
    'signup.businessDetails.uploadPassport': 'Upload Passport',
    'signup.businessDetails.uploadVisa': 'Upload Visa',
    'signup.businessDetails.uploadTradeLicense': 'Upload Trade License',
    'signup.businessDetails.tradeLicenseFormats': 'Supported formats: PDF, JPG, PNG (Max 10MB)',
    'signup.businessDetails.dragDropOrClick': 'Drag and drop or click to browse',
    'signup.businessDetails.chooseFile': 'Choose File',
    'signup.businessDetails.accountType': 'Account Type',
    'signup.businessDetails.accountTypePlaceholder': 'Select account type',
    'signup.businessDetails.agency': 'Agency',
    'signup.businessDetails.agencyDescription': 'For advertising agencies managing multiple clients',
    'signup.businessDetails.directAdvertiser': 'Direct Advertiser',
    'signup.businessDetails.directAdvertiserDescription': 'For businesses advertising their own products/services',

    // Address & Contact
    'signup.addressContact.accountType': 'Account Type',
    'signup.addressContact.accountTypeDescription': 'Choose the type that best describes your business',
    'signup.addressContact.selectAccountType': 'Select your account type',
    'signup.addressContact.agency': 'Advertising Agency',
    'signup.addressContact.agencyDescription': 'Manage campaigns for multiple clients',
    'signup.addressContact.direct': 'Direct Advertiser',
    'signup.addressContact.directDescription': 'Advertise your own business',
    'signup.addressContact.agencyFeatures': 'Agency Features:',
    'signup.addressContact.agencyFeature1': 'Multi-client management dashboard',
    'signup.addressContact.agencyFeature2': 'Bulk campaign creation tools',
    'signup.addressContact.agencyFeature3': 'Advanced reporting across clients',
    'signup.addressContact.agencyFeature4': 'Dedicated account manager',
    'signup.addressContact.directFeatures': 'Direct Advertiser Features:',
    'signup.addressContact.directFeature1': 'Streamlined single-business interface',
    'signup.addressContact.directFeature2': 'Easy-to-use campaign builder',
    'signup.addressContact.directFeature3': 'Real-time performance tracking',
    'signup.addressContact.directFeature4': 'Budget management tools',
    'signup.addressContact.companyAddress': 'Company Address',
    'signup.addressContact.streetAddress': 'Street Address',
    'signup.addressContact.streetAddressPlaceholder': 'Enter your complete street address',
    'signup.addressContact.city': 'City',
    'signup.addressContact.cityPlaceholder': 'Enter city',
    'signup.addressContact.emirate': 'Emirate',
    'signup.addressContact.selectEmirate': 'Select emirate',
    'signup.addressContact.country': 'Country',
    'signup.addressContact.selectCountry': 'Select country',
    'signup.addressContact.poBox': 'P.O. Box',
    'signup.addressContact.poBoxPlaceholder': 'Enter P.O. Box (optional)',
    'signup.addressContact.poBoxNote': 'Optional - For postal correspondence',
    'signup.addressContact.contactInformation': 'Contact Information',
    'signup.addressContact.landline': 'Landline / Alternate Phone',
    'signup.addressContact.landlinePlaceholder': '+971 4 123 4567',
    'signup.addressContact.landlineNote': 'Office landline or alternate contact number',
    'signup.addressContact.socialMediaLinks': 'Social Media Links',
    'signup.addressContact.socialMediaNote': 'Add your social media profile links (optional)',
    'signup.addressContact.facebook': 'Facebook',
    'signup.addressContact.facebookPlaceholder': 'https://facebook.com/yourpage',
    'signup.addressContact.twitter': 'X (Twitter)',
    'signup.addressContact.twitterPlaceholder': 'https://x.com/yourhandle',
    'signup.addressContact.tiktok': 'TikTok',
    'signup.addressContact.tiktokPlaceholder': 'https://tiktok.com/@yourhandle',
    'signup.addressContact.instagram': 'Instagram',
    'signup.addressContact.instagramPlaceholder': 'https://instagram.com/yourhandle',
    'signup.addressContact.addressVerification': 'Address Verification',
    'signup.addressContact.addressVerificationNote': 'This address will be used for official correspondence and may be verified as part of the account approval process. Please ensure all details are accurate.',
    'signup.addressContact.emirates.abudhabi': 'Abu Dhabi',
    'signup.addressContact.emirates.dubai': 'Dubai',
    'signup.addressContact.emirates.sharjah': 'Sharjah',
    'signup.addressContact.emirates.ajman': 'Ajman',
    'signup.addressContact.emirates.uaq': 'Umm Al Quwain',
    'signup.addressContact.emirates.rak': 'Ras Al Khaimah',
    'signup.addressContact.emirates.fujairah': 'Fujairah',
    'signup.addressContact.countries.uae': 'United Arab Emirates',
    'signup.addressContact.countries.saudi': 'Saudi Arabia',
    'signup.addressContact.countries.qatar': 'Qatar',
    'signup.addressContact.countries.kuwait': 'Kuwait',
    'signup.addressContact.countries.bahrain': 'Bahrain',
    'signup.addressContact.countries.oman': 'Oman'
  },
  ar: {
    // Navigation
    'nav.signIn': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ الآن',
    'nav.adPlatform': 'منصة الإعلانات',
    'nav.platforms': 'المنصات',
    'nav.platforms.description': 'تلفزيون، راديو، مطبوعات ووسائل التواصل',
    'nav.howItWorks': 'كيف يعمل',
    'nav.howItWorks.description': 'عملية بسيطة من 4 خطوات',
    'nav.programs': 'البرامج',
    'nav.programs.description': 'فترات إعلانية مميزة',
    'nav.analytics': 'التحليلات',
    'nav.analytics.description': 'رؤى الأداء',
    'nav.pricing': 'الأسعار',
    'nav.pricing.description': 'أسعار شفافة',
    'nav.contact': 'اتصل بنا',
    'nav.contact.description': 'تواصل معنا',
    
    // Hero Section
    'hero.title': 'أعلن في أي مكان، في أي وقت',
    'hero.subtitle': 'التلفزيون والراديو والمطبوعات ووسائل التواصل الاجتماعي في منصة واحدة',
    'hero.getStarted': 'ابدأ الآن',
    'hero.bookSlot': 'احجز مساحتك الإعلانية',
    'hero.alt': 'بطل منصة الإعلان لوسائل الإعلام في دبي',
    
    // CTA Section
    'cta.title': 'جاهز لتحويل إعلاناتك؟',
    'cta.subtitle': 'انضم إلى آلاف الشركات التي تستخدم منصتنا بالفعل للوصول إلى المزيد من العملاء وتحقيق نتائج أفضل عبر جميع القنوات الإعلامية.',
    'cta.bookDemo': 'احجز عرضاً مجانياً',
    'cta.createCampaign': 'أنشئ حملتك',
    'cta.support.title': 'دعم 24/7',
    'cta.support.description': 'احصل على المساعدة متى احتجتها',
    'cta.setup.title': 'إعداد سريع',
    'cta.setup.description': 'أطلق حملاتك في دقائق',
    'cta.results.title': 'نتائج مثبتة',
    'cta.results.description': 'تحسن بمتوسط 200% في العائد على الاستثمار',
    
    // Contact Section
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'لديك أسئلة حول منصتنا؟ فريق خبراء الإعلان لدينا هنا لمساعدتك في إنشاء حملات ناجحة عبر جميع القنوات الإعلامية.',
    'contact.liveChat': 'دردشة مباشرة',
    'contact.liveChat.description': 'احصل على مساعدة فورية من فريق الدعم',
    'contact.startChat': 'ابدأ الدردشة',
    'contact.callUs': 'اتصل بنا',
    'contact.callUs.description': 'تحدث مع أخصائي إعلانات',
    'contact.emailSupport': 'دعم البريد الإلكتروني',
    'contact.emailSupport.description': 'أرسل لنا أسئلتك',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.chatNow': 'ادردش الآن',
    'contact.phone': '1-800-ADS-HELP',
    'contact.phone.hours': 'الإثنين - الجمعة: 9 صباحاً - 6 مساءً بتوقيت الشرق',
    'contact.email': 'support@adplatform.com',
    'contact.firstName': 'الاسم الأول',
    'contact.lastName': 'اسم العائلة',
    'contact.email_label': 'البريد الإلكتروني',
    'contact.company': 'الشركة',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.firstName.placeholder': 'أحمد',
    'contact.lastName.placeholder': 'علي',
    'contact.email.placeholder': 'ahmed@company.com',
    'contact.company.placeholder': 'اسم الشركة',
    'contact.subject.placeholder': 'كيف يمكننا مساعدتك؟',
    'contact.message.placeholder': 'أخبرنا عن احتياجاتك الإعلانية...',
    'contact.submit': 'إرسال الرسالة',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.q1': 'كم من الوقت يستغرق إطلاق الحملة؟',
    'contact.faq.a1': 'يمكن إطلاق معظم الحملات خلال 24-48 ساعة بعد الموافقة على المحتوى وتأكيد الدفع.',
    'contact.faq.q2': 'ما هي المنصات التي تدعمونها؟',
    'contact.faq.a2': 'ندعم التلفزيون والراديو والوسائل المطبوعة وجميع منصات وسائل التواصل الاجتماعي الرئيسية بما في ذلك فيسبوك وإنستغرام وتويتر ولينكدإن.',
    'contact.faq.q3': 'هل يمكنني تتبع أداء الحملة؟',
    'contact.faq.a3': 'نعم! توفر لوحة التحليلات الخاصة بنا تتبعاً في الوقت الفعلي للوصول والتفاعل والتحويلات والعائد على الاستثمار عبر جميع المنصات.',
    'contact.faq.q4': 'هل هناك حد أدنى للميزانية المطلوبة؟',
    'contact.faq.a4': 'تختلف الحدود الدنيا للميزانية حسب المنصة. يمكن أن تبدأ حملات وسائل التواصل الاجتماعي من 500 دولار، بينما التلفزيون والراديو لديهما حدود أدنى أعلى بناءً على حجم السوق.',
    
    // Platform Selection
    'platform.title': 'اختر منصتك',
    'platform.tv': 'التلفزيون',
    'platform.radio': 'الراديو',
    'platform.print': 'الوسائل المطبوعة',
    'platform.social': 'وسائل التواصل الاجتماعي',
    
    // Footer
    'footer.brand': 'Sama TV',
    'footer.description': 'منصة الإعلان الشاملة التي تربط علامتك التجارية بالجماهير عبر قنوات التلفزيون والراديو والمطبوعات ووسائل التواصل الاجتماعي.',
    'footer.newsletter.title': 'ابق على اطلاع',
    'footer.newsletter.placeholder': 'أدخل بريدك الإلكتروني',
    'footer.newsletter.subscribe': 'اشترك',
    'footer.platform.title': 'المنصة',
    'footer.platform.howItWorks': 'كيف يعمل',
    'footer.platform.pricing': 'الأسعار',
    'footer.platform.programs': 'البرامج المميزة',
    'footer.platform.analytics': 'التحليلات',
    'footer.support.title': 'الدعم',
    'footer.support.help': 'مركز المساعدة',
    'footer.support.contact': 'اتصل بنا',
    'footer.support.chat': 'دردشة مباشرة',
    'footer.support.docs': 'التوثيق',
    'footer.company.title': 'الشركة',
    'footer.company.about': 'معلومات عنا',
    'footer.company.careers': 'الوظائف',
    'footer.company.press': 'الصحافة',
    'footer.company.blog': 'المدونة',
    'footer.legal.privacy': 'سياسة الخصوصية',
    'footer.legal.terms': 'شروط الخدمة',
    'footer.legal.cookies': 'سياسة ملفات تعريف الارتباط',
    'footer.legal.compliance': 'الامتثال',
    'footer.followUs': 'تابعنا:',
    'footer.copyright': '© 2024 Sama TV. جميع الحقوق محفوظة.',
    
    // How It Works
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.subtitle': 'اجعل حملتك الإعلانية تعمل في أربع خطوات بسيطة فقط. عمليتنا المبسطة تجعل من السهل الوصول إلى جمهورك عبر أي منصة.',
    'howItWorks.step1.title': 'اختر المنصة',
    'howItWorks.step1.description': 'اختر من التلفزيون أو الراديو أو المطبوعات أو وسائل التواصل الاجتماعي حسب أهداف حملتك',
    'howItWorks.step2.title': 'اختر البرنامج / الفترة الزمنية',
    'howItWorks.step2.description': 'تصفح البرامج والفترات الزمنية المتاحة التي تناسب جمهورك المستهدف',
    'howItWorks.step3.title': 'ارفع محتوى الإعلان',
    'howItWorks.step3.description': 'ارفع أصولك الإبداعية أو استخدم قوالبنا لإنشاء إعلانات مقنعة',
    'howItWorks.step4.title': 'أكد وادفع',
    'howItWorks.step4.description': 'راجع تفاصيل حملتك وقم بالدفع الآمن لإطلاق إعلاناتك',
    
    // Featured Programs
    'featured.title': 'البرامج والفترات المميزة',
    'featured.subtitle': 'اكتشف فرص الإعلان الأكثر شعبية عبر جميع المنصات. هذه الفترات المميزة تقدم أفضل قيمة وتفاعل مع الجمهور.',
    'featured.primeTime': 'الوقت الذهبي',
    'featured.views': 'مشاهدة',
    'featured.rating': 'تقييم',
    'featured.starting': 'يبدأ من',
    'featured.bookSlot': 'احجز هذه الفترة',
    'featured.viewAllSlots': 'عرض جميع الفترات المتاحة',
    'featured.viewers': 'مشاهد',
    'featured.listeners': 'مستمع',
    'featured.readers': 'قارئ',
    'featured.reach': 'وصول',
    
    // Program Names
    'programs.morningNews': 'برنامج أخبار الصباح',
    'programs.driveTime': 'راديو وقت القيادة',
    'programs.weekendSports': 'برنامج الرياضة الأسبوعي',
    'programs.businessWeekly': 'الأعمال الأسبوعية',
    'programs.eveningEntertainment': 'الترفيه المسائي',
    'programs.socialCampaign': 'حزمة الحملة الاجتماعية',
    
    // Time Slots
    'timeSlots.morning': '7:00 - 9:00 صباحاً',
    'timeSlots.evening': '5:00 - 7:00 مساءً',
    'timeSlots.afternoon': 'السبت 2:00 ظهراً',
    'timeSlots.monday': 'إصدار الاثنين',
    'timeSlots.primeTime': '8:00 - 10:00 مساءً',
    'timeSlots.weekCampaign': 'حملة 7 أيام',
    
    // Platforms
    'platforms.television': 'التلفزيون',
    'platforms.radio': 'الراديو',
    'platforms.print': 'الطباعة',
    'platforms.socialMedia': 'وسائل التواصل الاجتماعي',
    
    // Categories
    'categories.news': 'الأخبار',
    'categories.talk': 'الحديث',
    'categories.sports': 'الرياضة',
    'categories.business': 'الأعمال',
    'categories.entertainment': 'الترفيه',
    'categories.digital': 'الرقمي',
    
    // Analytics
    'analytics.title': 'الوصول والتحليلات',
    'analytics.subtitle': 'احصل على رؤى مفصلة حول أداء حملتك مع التحليلات في الوقت الفعلي. تتبع الوصول والتفاعل والعائد على الاستثمار عبر جميع المنصات.',
    'analytics.totalReach': 'إجمالي الوصول',
    'analytics.avgEngagement': 'متوسط التفاعل',
    'analytics.conversionRate': 'معدل التحويل',
    'analytics.roi': 'العائد على الاستثمار',
    'analytics.fromLastMonth': 'من الشهر الماضي',
    'analytics.reachByPlatform': 'الوصول حسب المنصة',
    'analytics.engagementRates': 'معدلات التفاعل',
    'analytics.audienceDemographics': 'التركيبة السكانية للجمهور',
    'analytics.ageGroups': 'الفئات العمرية',
    'analytics.gender': 'الجنس',
    'analytics.location': 'الموقع',
    'analytics.platform.tv': 'التلفزيون',
    'analytics.platform.radio': 'الراديو',
    'analytics.platform.print': 'المطبوعات',
    'analytics.platform.social': 'وسائل التواصل',
    'analytics.age.18-24': '18-24',
    'analytics.age.25-34': '25-34',
    'analytics.age.35-44': '35-44',
    'analytics.age.45+': '45+',
    'analytics.gender.male': 'ذكر',
    'analytics.gender.female': 'أنثى',
    'analytics.location.urban': 'UAE',
    'analytics.location.suburban': 'GCC',
    'analytics.location.rural': 'الشرق الأوسط',
    'analytics.location.other': 'دول أخرى',
    
    // Testimonials
    'testimonials.title': 'قصص النجاح',
    'testimonials.subtitle': 'شاهد كيف حققت الشركات مثل شركتك نتائج رائعة باستخدام حلول الإعلان متعدد المنصات الخاص بنا.',
    
    // Testimonial 1 - Sarah Johnson
    'testimonials.sarah.name': 'سارة جونسون',
    'testimonials.sarah.company': 'تك ستارت المحدودة',
    'testimonials.sarah.role': 'مديرة التسويق',
    'testimonials.sarah.content': 'وفرت لنا المنصة الموحدة 40% من ميزانية الإعلان مع زيادة وصولنا بنسبة 200%. لوحة التحليلات تمنحنا رؤى لم نحصل عليها من قبل.',
    'testimonials.sarah.campaign': 'إطلاق متعدد المنصات',
    'testimonials.sarah.results': '+200% وصول، توفير 40% في التكاليف',
    
    // Testimonial 2 - Michael Chen
    'testimonials.michael.name': 'مايكل تشين',
    'testimonials.michael.company': 'ريتيل ماكس',
    'testimonials.michael.role': 'مدير العلامة التجارية',
    'testimonials.michael.content': 'كانت إدارة الحملات عبر التلفزيون والراديو ووسائل التواصل الاجتماعي كابوساً. هذه المنصة جعلت الأمر سلساً وتحسن عائد الاستثمار بنسبة 150%.',
    'testimonials.michael.campaign': 'حملة موسم العطلات',
    'testimonials.michael.results': '+150% عائد استثمار، 3.2 مليون انطباع',
    
    // Testimonial 3 - Emily Rodriguez
    'testimonials.emily.name': 'إيميلي رودريغيز',
    'testimonials.emily.company': 'محلي إيتس',
    'testimonials.emily.role': 'المالكة',
    'testimonials.emily.content': 'كشركة صغيرة، اعتقدت أن الإعلان متعدد المنصات بعيد المنال. هذه المنصة جعلته ميسور التكلفة وفعالاً. زادت المبيعات بنسبة 85% في الربع الأول.',
    'testimonials.emily.campaign': 'حملة توعية محلية',
    'testimonials.emily.results': '+85% نمو في المبيعات',
    
    // Testimonial 4 - David Thompson
    'testimonials.david.name': 'ديفيد تومسون',
    'testimonials.david.company': 'فيت لايف جيمز',
    'testimonials.david.role': 'رئيس التسويق',
    'testimonials.david.content': 'قدرات الاستهداف لا تصدق. وصلنا بالضبط للجمهور المناسب عبر جميع القنوات ورأينا زيادة 300% في عضوية النادي الرياضي.',
    'testimonials.david.campaign': 'ترويج تحدي اللياقة',
    'testimonials.david.results': '+300% عضوية',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك! إليك ما يحدث مع حملاتك.',
    'dashboard.mediaIntelligence': 'الذكاء الإعلامي',
    'dashboard.user': 'أحمد علي',
    'dashboard.profile': 'الملف الشخصي',
    'dashboard.settings': 'الإعدادات',
    'dashboard.logout': 'تسجيل الخروج',
    'dashboard.overview': 'نظرة عامة',
    'dashboard.newBooking': 'حجز جديد',
    'dashboard.myBookings': 'حجوزاتي',
    'dashboard.myBookings.description': 'سيظهر تاريخ حجوزاتك هنا',
    'dashboard.packages': 'الباقات المتاحة',
    'dashboard.packages.description': 'باقات وعروض إعلانية خاصة',
    'dashboard.invoices': 'الفواتير',
    'dashboard.invoices.description': 'تاريخ الفواتير والمدفوعات',
    'dashboard.analytics': 'التحليلات',
    'dashboard.support': 'الدعم',
    
    // Dashboard Stats
    'stats.totalCampaigns': 'إجمالي الحملات',
    'stats.activeAds': 'الإعلانات النشطة',
    'stats.totalReach': 'إجمالي الوصول',
    'stats.monthlySpend': 'الإنفاق الشهري',
    'stats.fromLastMonth': 'من الشهر الماضي',
    
    // Booking Status
    'status.confirmed': 'مؤكد',
    'status.creativeReview': 'مراجعة الإبداع',
    'status.paymentDue': 'دفع مستحق',
    'status.pending': 'في الانتظار',
    'status.approved': 'موافق عليه',
    'status.rejected': 'مرفوض',
    
    // Media Selection
    'mediaSelection.title': 'اختر منفذ الإعلام',
    'mediaSelection.subtitle': 'اختر من شركائنا الإعلاميين المميزين',
    'mediaSelection.search': 'البحث عن منافذ إعلامية...',
    'mediaSelection.all': 'الكل',
    'mediaSelection.tv': 'التلفزيون',
    'mediaSelection.radio': 'الراديو',
    'mediaSelection.print': 'المطبوعات',
    'mediaSelection.digital': 'الرقمية',
    'mediaSelection.reach': 'الوصول:',
    'mediaSelection.select': 'اختر',
    'mediaSelection.selected': 'محدد:',
    'mediaSelection.noResults': 'لم يتم العثور على منافذ',
    'mediaSelection.noResults.description': 'جرب تعديل معايير البحث أو التصفية',
    'mediaSelection.continue': 'متابعة',
    'mediaSelection.back': 'رجوع',
    'mediaSelection.step': 'خطوة',
    'mediaSelection.of': 'من',
    'mediaSelection.allMedia': 'جميع الوسائط',
    'mediaSelection.tvChannels': 'القنوات التلفزيونية',
    'mediaSelection.radioStations': 'الراديو',
    'mediaSelection.printMedia': 'المطبوعات',
    'mediaSelection.digitalPlatforms': 'المنصات الرقمية',
    
    // Media Outlet Descriptions  
    'media.dubaiTV.desc': 'قناة ترفيهية عربية رائدة',
    'media.samaDubai.desc': 'قناة أسلوب الحياة والثقافة في دبي',
    'media.dubaiSports.desc': 'الرياضة والأحداث المباشرة',
    'media.dubaiOne.desc': 'قناة باللغة الإنجليزية',
    'media.noorDubai.desc': 'البرامج الإسلامية والثقافية',
    'media.dubaiFM.desc': 'الموسيقى والترفيه',
    'media.dubaiEye.desc': 'إذاعة الحوار والأخبار',
    'media.alBayan.desc': 'صحيفة عربية يومية',
    'media.emiratesToday.desc': 'صحيفة الأعمال الإنجليزية',
    'media.gulfNews.desc': 'الصحيفة الإنجليزية الرائدة',
    'media.dubaiPortal.desc': 'البوابة الرسمية لحكومة دبي',
    'media.dubaiTourism.desc': 'منصة السياحة والسفر',
    'media.socialBundle.desc': 'انستغرام، فيسبوك، تويتر',
    'media.viewers': 'مشاهد',
    'media.listeners': 'مستمع',
    'media.readers': 'قارئ',
    'media.visitors': 'زائر',
    'media.users': 'مستخدم',
    'media.impressions': 'انطباع',
    
    // Media Outlet Names
    'media.dubaiTV.name': 'Sama TV',
    'media.samaDubai.name': 'Dubai TV', 
    'media.dubaiSports.name': 'Dubai One TV',
    'media.dubaiOne.name': 'Dubai Sport TV',
    'media.noorDubai.name': 'Noor Dubai Radio ',
    'media.dubaiFM.name': 'Dubai Radio ',
    'media.dubaiEye.name': 'Noor Dubai Radio',
    'media.alBayan.name': 'Emarat Al Youm',
    'media.emiratesToday.name': 'Al Bayan',
    'media.gulfNews.name': ' Emarat Al Youm',
    'media.dubaiPortal.name': 'Awan',
    'media.dubaiTourism.name': 'Awan',
    'media.socialBundle.name': 'Awan',
    
    // Media Types
    'media.type.tv': 'تلفزيون',
    'media.type.radio': 'إذاعة',
    'media.type.print': 'مطبوعات',
    'media.type.digital': 'رقمي',
    
    // Program Names and Details
    'program.morningDubai.name': 'مقابلة',
    'program.morningDubai.category': 'الأخبار والشؤون الجارية',
    'program.cityPulse.name': 'تقرير إخباري تلفزيوني',
    'program.cityPulse.category': 'أسلوب الحياة',
    'program.primeTimeNews.name': 'تقرير إخباري تلفزيوني',
    'program.primeTimeNews.category': 'الأخبار',
    'program.businessToday.name': 'مقابلة',
    'program.businessToday.category': 'الأعمال',
    'program.hours': 'ساعات',
    'program.hour': 'ساعة',
    'program.minutes': 'دقائق',
    'program.viewers': 'مشاهد',
    'program.adults': 'البالغون',
    'program.professionals': 'المهنيون',
    
    // Pricing & Packages
    'pricing.title': 'الأسعار والباقات',
    'pricing.subtitle': 'خصص حجزك مع الإضافات والباقات',
    'pricing.step': 'الخطوة 3 من 6',
    'pricing.back': 'رجوع',
    'pricing.basePricing': 'التسعير الأساسي',
    'pricing.basePrice': 'السعر الأساسي',
    'pricing.at': 'في',
    'pricing.enhanceCampaign': 'حسّن حملتك',
    'pricing.seasonalPackages': 'الباقات الموسمية',
    'pricing.pricingSummary': 'ملخص الأسعار',
    'pricing.totalPrice': 'السعر الإجمالي',
    'pricing.youSave': 'توفر',
    'pricing.discount': 'خصم',
    'pricing.continueToMaterial': 'متابعة إلى المواد الإعلانية',
    'pricing.proTip': 'نصيحة احترافية:',
    'pricing.proTipText': 'الباقات الموسمية تقدم أفضل قيمة وتشمل فوائد إضافية مثل الموافقة الأولوية والتحليلات المحسنة.',
    
    // Add-ons
    'addons.peakHour.name': 'تعزيز ساعات الذروة',
    'addons.peakHour.desc': 'رؤية محسنة خلال الوقت الذهبي',
    'addons.weekend.name': 'باقة عطلة نهاية الأسبوع المميزة', 
    'addons.weekend.desc': 'فترات إضافية في عطلة نهاية الأسبوع',
    'addons.multiSlot.name': 'خصم متعدد الفترات',
    'addons.multiSlot.desc': 'خصم 10% عند حجز 3+ فترات',
    'addons.analytics.name': 'تحليلات الجمهور',
    'addons.analytics.desc': 'تقارير مفصلة عن المشاهدة',
    
    // Seasonal Packages
    'packages.ramadan.name': 'باقة رمضان الخاصة',
    'packages.ramadan.desc': 'مثالية لحملات رمضان مع الفترات المميزة',
    'packages.ramadan.feature1': '5 فترات زمنية مميزة',
    'packages.ramadan.feature2': 'توقيت الإفطار والسحور',
    'packages.ramadan.feature3': 'إبداعات رمضانية مخصصة',
    'packages.ramadan.feature4': 'تحليلات محسنة',
    'packages.ramadan.feature5': 'موافقة أولوية',
    'packages.ramadan.badge': 'الأكثر شعبية',
    
    'packages.fifa.name': 'باقة كأس العالم فيفا',
    'packages.fifa.desc': 'إعلانات رياضية مركزة خلال الأحداث الكبرى',
    'packages.fifa.feature1': '8 فترات القنوات الرياضية',
    'packages.fifa.feature2': 'أولوية يوم المباراة',
    'packages.fifa.feature3': 'قوالب إبداعية رياضية',
    'packages.fifa.feature4': 'أداء في الوقت الفعلي',
    'packages.fifa.feature5': 'ترويج متقاطع لوسائل التواصل',
    'packages.fifa.badge': 'وقت محدود',
    
    'packages.eid.name': 'عرض احتفال العيد الخاص',
    'packages.eid.desc': 'حملات احتفالية لاحتفالات العيد',
    'packages.eid.feature1': '4 فترات الوقت الذهبي',
    'packages.eid.feature2': 'مجموعة إبداعات العيد',
    'packages.eid.feature3': 'دعم متعدد اللغات',
    'packages.eid.feature4': 'تحليلات المهرجان',
    'packages.eid.feature5': 'موافقة سريعة',
    'packages.eid.badge': 'جديد',
    
    // Ad Material Upload
    'adMaterial.title': 'مواد الإعلان',
    'adMaterial.subtitle': 'ارفع إعلانك أو دعنا ننشئه لك',
    'adMaterial.step': 'الخطوة 4 من 6',
    'adMaterial.back': 'رجوع',
    'adMaterial.uploadMyAd': 'رفع إعلاني',
    'adMaterial.requestDesign': 'طلب تصميم من MI',
    'adMaterial.uploadYourAd': 'ارفع إعلانك',
    'adMaterial.dragDrop': 'اسحب وأفلت ملفك هنا، أو انقر للتصفح',
    'adMaterial.acceptedFormats': 'التنسيقات المقبولة',
    'adMaterial.chooseFile': 'اختر ملف',
    'adMaterial.replaceFile': 'استبدال الملف',
    'adMaterial.reviewProcess': 'عملية المراجعة',
    'adMaterial.reviewProcessDesc': 'ستتم مراجعة المواد المرفوعة من قبل فريقنا الإبداعي للتأكد من أنها تلبي معايير البث ومتطلبات الجودة.',
    'adMaterial.chooseTemplate': 'اختر قالباً',
    'adMaterial.customizeTemplate': 'تخصيص القالب',
    'adMaterial.templatePreview': 'معاينة القالب',
    'adMaterial.continueToReview': 'متابعة للمراجعة',
    
    // Template Names
    'templates.tv30s.name': 'إعلان تلفزيوني 30 ثانية',
    'templates.tv30s.desc': 'قالب إعلان تلفزيوني احترافي مع حركات حديثة',
    'templates.tv60s.name': 'إعلان تلفزيوني 60 ثانية', 
    'templates.tv60s.desc': 'إعلان تلفزيوني مطول لعرض المنتج بالتفصيل',
    'templates.radio15s.name': 'جنجل إذاعي 15 ثانية',
    'templates.radio15s.desc': 'جنجل إذاعي جذاب مع تعليق صوتي احترافي',
    'templates.radio30s.name': 'إعلان إذاعي 30 ثانية',
    'templates.radio30s.desc': 'إعلان إذاعي كامل مع موسيقى وسرد',
    'templates.printFull.name': 'إعلان مطبوع صفحة كاملة',
    'templates.printFull.desc': 'تصميم إعلان احترافي لصفحة كاملة في الجريدة',
    'templates.printHalf.name': 'إعلان مطبوع نصف صفحة',
    'templates.printHalf.desc': 'إعلان مدمج لنصف صفحة في الجريدة',
    'templates.digitalStory.name': 'قصة إنستغرام',
    'templates.digitalStory.desc': 'قالب قصة إنستغرام جذاب مع حركات',
    'templates.digitalPost.name': 'منشور وسائل التواصل',
    'templates.digitalPost.desc': 'تصميم منشور جذاب لوسائل التواصل الاجتماعي',
    
    // Customization Form
    'customize.companyName': 'اسم العلامة التجارية / الشركة',
    'customize.companyNamePlaceholder': 'أدخل اسم شركتك',
    'customize.productName': 'اسم المنتج / الخدمة',
    'customize.productNamePlaceholder': 'أدخل اسم المنتج أو الخدمة',
    'customize.slogan': 'الشعار / الرسالة',
    'customize.sloganPlaceholder': 'أدخل رسالتك الأساسية أو الشعار',
    'customize.colors': 'الألوان / النمط المفضل',
    'customize.colorPlaceholder': 'اختر نظام الألوان',
    'customize.language': 'اللغة',
    'customize.logoUpload': 'رفع الشعار (اختياري)',
    'customize.logoFormats': 'PNG، JPG، أو SVG (حد أقصى 5 ميجابايت)',
    'customize.yourCompany': 'شركتك',
    'customize.yourMessage': 'رسالتك هنا',
    
    // Color Schemes
    'colors.professional': 'احترافي (أزرق ورمادي)',
    'colors.vibrant': 'حيوي (أحمر وبرتقالي)',
    'colors.elegant': 'أنيق (أسود وذهبي)',
    'colors.fresh': 'منعش (أخضر وأبيض)',
    'colors.luxury': 'فاخر (بنفسجي وفضي)',
    'colors.custom': 'مخصص (حدد في التعليقات)',
    
    // Languages
    'lang.english': 'الإنجليزية',
    'lang.arabic': 'العربية',
    'lang.both': 'كلاهما (ثنائي اللغة)',
    
    // Durations
    'duration.seconds': 'ثانية',
    'duration.fullPage': 'صفحة كاملة',
    'duration.halfPage': 'نصف صفحة',
    'duration.static': 'ثابت',
    
    // Program Time Slot
    'programTime.title': 'اختر البرنامج والوقت',
    'programTime.subtitle': 'اختر التوقيت المفضل لديك',
    'programTime.selectedDate': 'التاريخ المحدد',
    'programTime.selectedDates': 'التواريخ المحددة',
    'programTime.to': 'إلى',
    'programTime.availablePrograms': 'البرامج المتاحة',
    'programTime.availableTimeSlots': 'الفترات الزمنية المتاحة',
    'programTime.booked': 'محجوز',
    'programTime.selectProgram': 'يرجى اختيار برنامج أولاً',
    'programTime.selectTimeSlot': 'يرجى اختيار فترة زمنية',
    'programTime.back': 'رجوع',
    'programTime.continue': 'متابعة إلى الأسعار',
    'programTime.step2of6': 'خطوة 2 من 6',
    'programTime.available': 'متاح',
    'programTime.selectDate': 'اختر التاريخ',
    'programTime.days': 'أيام',
    'programTime.premium': 'مميز',
    'programTime.morning': 'صباحي',
    'programTime.afternoon': 'بعد الظهر',
    'programTime.evening': 'مسائي',
        'programTime.late': 'وقت متأخر من الليل',
    'programTime.timeSlotLabel': 'فترة زمنية',
    'programTime.hour': 'ساعة',
    'programTime.programs': 'البرامج',
    'programTime.timeSlots': 'الفترات الزمنية',
    'programTime.target': 'الهدف',
    'programTime.day': 'يوم',
    'programTime.selected': 'محدد',
    'programTime.at': 'في',
    'programTime.basePrice': 'السعر الأساسي',
    'programTime.total': 'الإجمالي',
    
    // Payment
    'payment.title': 'الدفع والسداد',
    'payment.subtitle': 'أكمل حجزك بأمان',
    'payment.step': 'الخطوة 6 من 6',
    'payment.back': 'رجوع',
    'payment.method': 'طريقة الدفع',
    'payment.creditCard': 'بطاقة ائتمان / خصم',
    'payment.creditCardDesc': 'فيزا، ماستركارد، أمريكان إكسبريس',
    'payment.instant': 'فوري',
    'payment.bankTransfer': 'تحويل بنكي',
    'payment.bankTransferDesc': 'تحويل مباشر من بنك إلى بنك',
    'payment.days1to2': '1-2 أيام',
    'payment.digitalWallet': 'محفظة رقمية',
    'payment.digitalWalletDesc': 'أبل باي، جوجل باي، سامسونج باي',
    'payment.cardDetails': 'تفاصيل البطاقة',
    'payment.cardNumber': 'رقم البطاقة',
    'payment.expiryDate': 'تاريخ انتهاء الصلاحية',
    'payment.cvv': 'رمز الأمان',
    'payment.cardholderName': 'اسم حامل البطاقة',
    'payment.cardNamePlaceholder': 'الاسم كما يظهر على البطاقة',
    'payment.bankTransferDetails': 'تفاصيل التحويل البنكي',
    'payment.transferTo': 'التحويل إلى:',
    'payment.bank': 'البنك',
    'payment.accountName': 'اسم الحساب',
    'payment.accountNumber': 'رقم الحساب',
    'payment.swiftCode': 'رمز SWIFT',
    'payment.iban': 'رقم الآيبان',
    'payment.referenceNumber': 'رقم المرجع',
    'payment.referenceNote': 'يرجى تضمين رقم المرجع هذا مع التحويل',
    'payment.digitalWalletSelect': 'اختر محفظتك الرقمية المفضلة لإكمال الدفع.',
    'payment.applePay': 'أبل باي',
    'payment.googlePay': 'جوجل باي',
    'payment.samsungPay': 'سامسونج باي',
    'payment.securePayment': 'دفع آمن',
    'payment.securePaymentDesc': 'معلومات الدفع الخاصة بك مشفرة وآمنة. نستخدم تشفير SSL المعياري ولا نحتفظ بتفاصيل الدفع الخاصة بك.',
    'payment.paymentSummary': 'ملخص الدفع',
    'payment.mediaOutlet': 'المنصة الإعلامية',
    'payment.program': 'البرنامج',
    'payment.dateTime': 'التاريخ والوقت',
    'payment.subtotal': 'المجموع الفرعي',
    'payment.vat': 'ضريبة القيمة المضافة (5%)',
    'payment.totalAmount': 'المبلغ الإجمالي',
    'payment.processing': 'جارٍ المعالجة...',
    'payment.payButton': 'ادفع',
    'payment.bankTransferNote': 'ملاحظة التحويل البنكي',
    'payment.bankTransferNoteDesc': 'سيتم تأكيد حجزك بمجرد استلام الدفعة (1-2 أيام عمل).',
    'payment.sslEncrypted': 'مشفر بـ SSL 256-bit',
    'programTime.daySelected': 'يوم محدد',
    'programTime.daysSelected': 'أيام محددة',
    'programTime.pricingPerDay': 'سيتم احتساب السعر لكل يوم',
    'programTime.noDateSelected': 'لم يتم اختيار تاريخ',
    
    // Booking Success
    'pricing.selectPackage': 'اختر الباقة',
    'pricing.mostPopular': 'الأكثر شعبية',
    
    // Booking Success
    'success.title': 'تم تأكيد الحجز!',
    'success.subtitle': 'تم تقديم حجز إعلانك بنجاح',
    'success.bookingNumber': 'رقم الحجز',
    'success.nextSteps': 'ما هي الخطوات التالية؟',
    'success.approval': 'موافقة الإبداع',
    'success.approval.description': 'سيراجع فريقنا مواد إعلانك',
    'success.scheduling': 'الجدولة',
    'success.scheduling.description': 'سيتم جدولة إعلانك للفترات المحددة',
    'success.goLive': 'البث المباشر',
    'success.goLive.description': 'سيبدأ بث إعلانك',
    'success.quickActions': 'إجراءات سريعة',
    'success.downloadInvoice': 'تحميل الفاتورة',
    'success.viewBooking': 'عرض تفاصيل الحجز',
    'success.newBooking': 'إنشاء حجز جديد',
    'success.dashboard': 'العودة للوحة التحكم',
    'success.bookingReference': 'رقم الحجز:',
    'success.bookingSummary': 'ملخص الحجز',
    'success.mediaOutlet': 'المنفذ الإعلامي',
    'success.program': 'البرنامج',
    'success.timeSlot': 'الفترة الزمنية',
    
    // SignUp Forms
    'signup.title': 'إنشاء حسابك',
    'signup.backToHome': 'العودة إلى الصفحة الرئيسية',
    'signup.description': 'أكمل عملية التسجيل لبدء الإعلان عبر قنوات متعددة',
    'signup.stepOf': 'خطوة {step} من {total}',
    'signup.percentComplete': '{percent}% مكتمل',

    // Step Titles
    'signup.steps.basicAccount': 'معلومات الحساب الأساسية',
    'signup.steps.businessDetails': 'تفاصيل الشركة / الأعمال',
    'signup.steps.userRole': 'دور المستخدم ونوعه',
    'signup.steps.accountTypeAddress': 'نوع الحساب وتفاصيل العنوان',
    'signup.steps.addressContact': 'العنوان وتفاصيل الاتصال',
    'signup.steps.paymentPreferences': 'تفضيلات الدفع',
    'signup.steps.complianceApproval': 'الامتثال والموافقة',
    'signup.subtitle': 'انضم إلى منصتنا الإعلانية',
    'signup.progress': 'الخطوة {{current}} من {{total}}',
    'signup.next': 'التالي',
    'signup.back': 'رجوع',
    'signup.submit': 'تقديم الطلب',
    'signup.success': 'تم تقديم التسجيل بنجاح! حسابك في انتظار المراجعة.',
    
    // Basic Account Info
    'signup.basicAccount.firstName': 'الاسم الأول',
    'signup.basicAccount.firstNamePlaceholder': 'أدخل اسمك الأول',
    'signup.basicAccount.lastName': 'الاسم الأخير',
    'signup.basicAccount.lastNamePlaceholder': 'أدخل اسمك الأخير',
    'signup.basicAccount.email': 'عنوان البريد الإلكتروني',
    'signup.basicAccount.emailPlaceholder': 'your.email@company.com',
    'signup.basicAccount.verify': 'تحقق',
    'signup.basicAccount.verified': 'متحقق منه',
    'signup.basicAccount.emailVerified': 'تم التحقق من البريد الإلكتروني بنجاح',
    'signup.basicAccount.mobile': 'رقم الهاتف المحمول',
    'signup.basicAccount.mobilePlaceholder': '+971 50 123 4567',
    'signup.basicAccount.sendOTP': 'إرسال رمز',
    'signup.basicAccount.mobileVerified': 'تم التحقق من رقم الهاتف بنجاح',
    'signup.basicAccount.password': 'كلمة المرور',
    'signup.basicAccount.passwordPlaceholder': 'أنشئ كلمة مرور قوية',
    'signup.basicAccount.confirmPassword': 'تأكيد كلمة المرور',
    'signup.basicAccount.confirmPasswordPlaceholder': 'أكد كلمة المرور',
    'signup.basicAccount.passwordStrength.weak': 'ضعيفة',
    'signup.basicAccount.passwordStrength.fair': 'مقبولة',
    'signup.basicAccount.passwordStrength.good': 'جيدة',
    'signup.basicAccount.passwordStrength.strong': 'قوية',
    'signup.basicAccount.passwordRequirements.length': 'على الأقل 8 أحرف',
    'signup.basicAccount.passwordRequirements.uppercase': 'حرف كبير واحد',
    'signup.basicAccount.passwordRequirements.lowercase': 'حرف صغير واحد',
    'signup.basicAccount.passwordRequirements.special': 'أرقام ورموز خاصة',
    'signup.basicAccount.passwordsMatch': 'كلمات المرور متطابقة',
    'signup.basicAccount.passwordsDontMatch': 'كلمات المرور غير متطابقة',
    'signup.basicAccount.preferredLanguage': 'اللغة المفضلة',
    'signup.basicAccount.languagePlaceholder': 'اختر لغتك المفضلة',
    'signup.basicAccount.english': 'English',
    'signup.basicAccount.arabic': 'العربية (Arabic)',
    
    // Business Details
    'signup.businessDetails.companyName': 'اسم الشركة / الوكالة',
    'signup.businessDetails.companyNamePlaceholder': 'أدخل اسم شركتك أو وكالتك',
    'signup.businessDetails.tradeLicenseNumber': 'رقم الرخصة التجارية',
    'signup.businessDetails.tradeLicenseNumberPlaceholder': 'أدخل رقم رخصتك التجارية',
    'signup.businessDetails.uploadTradeLicense': 'تحميل نسخة من الرخصة التجارية',
    'signup.businessDetails.dragDropTradeLicense': 'اسحب وأفلت رخصتك التجارية هنا، أو انقر للتصفح',
    'signup.businessDetails.tradeLicenseFormats': 'الصيغ المدعومة: PDF، JPG، PNG (الحد الأقصى 10 ميجابايت)',
    'signup.businessDetails.chooseFile': 'اختر ملف',
    'signup.businessDetails.idType': 'نوع الهوية',
    'signup.businessDetails.idTypeNote': 'اختر نوع وثيقة الهوية التي ستقوم بتحميلها',
    'signup.businessDetails.emiratesIdOption': 'الهوية الإماراتية',
    'signup.businessDetails.passportOption': 'جواز السفر',
    'signup.businessDetails.visaOption': 'التأشيرة',
    'signup.businessDetails.emiratesId': 'رقم الهوية الإماراتية',
    'signup.businessDetails.emiratesIdPlaceholder': 'أدخل رقم هويتك الإماراتية',
    'signup.businessDetails.passportNumber': 'رقم جواز السفر',
    'signup.businessDetails.passportNumberPlaceholder': 'أدخل رقم جواز سفرك',
    'signup.businessDetails.visaNumber': 'رقم التأشيرة',
    'signup.businessDetails.visaNumberPlaceholder': 'أدخل رقم تأشيرتك',
    'signup.businessDetails.uploadIdCopy': 'تحميل الهوية الإماراتية (الوجه والظهر)',
    'signup.businessDetails.uploadPassport': 'تحميل جواز السفر (صفحة الصورة)',
    'signup.businessDetails.uploadVisa': 'تحميل نسخة التأشيرة',
    'signup.businessDetails.uploadBothSides': 'قم بتحميل الوجه والظهر لهويتك',
    'signup.businessDetails.idFormats': 'الصيغ المدعومة: JPG، PNG، PDF (الحد الأقصى 5 ميجابايت لكل ملف)',
    'signup.businessDetails.chooseFiles': 'اختر ملفات',
    'signup.businessDetails.idUploadNote': 'يرجى تحميل صور واضحة لكلا جانبي هويتك الإماراتية أو صفحات جواز السفر.',
    
    // Address Contact
    'signup.addressContact.accountType': 'نوع الحساب',
    'signup.addressContact.accountTypeDescription': 'اختر النوع الذي يصف عملك بشكل أفضل',
    'signup.addressContact.selectAccountType': 'اختر نوع حسابك',
    'signup.addressContact.agency': 'وكالة إعلانية',
    'signup.addressContact.agencyDescription': 'إدارة الحملات لعملاء متعددين',
    'signup.addressContact.direct': 'معلن مباشر',
    'signup.addressContact.directDescription': 'الإعلان عن عملك الخاص',
    'signup.addressContact.agencyFeatures': 'ميزات حساب الوكالة',
    'signup.addressContact.directFeatures': 'ميزات المعلن المباشر',
    'signup.addressContact.agencyFeature1': 'إدارة حملات متعددة العملاء',
    'signup.addressContact.agencyFeature2': 'حلول العلامة البيضاء متاحة',
    'signup.addressContact.agencyFeature3': 'تقارير وتحليلات متقدمة',
    'signup.addressContact.agencyFeature4': 'أدوات فوترة العملاء والفواتير',
    'signup.addressContact.directFeature1': 'إنشاء حملة الخدمة الذاتية',
    'signup.addressContact.directFeature2': 'ترويج العلامة التجارية المباشر',
    'signup.addressContact.directFeature3': 'فوترة وتقارير مبسطة',
    'signup.addressContact.directFeature4': 'حلول إعلانية فعالة من حيث التكلفة',
    'signup.addressContact.companyAddress': 'عنوان الشركة',
    'signup.addressContact.streetAddress': 'عنوان الشارع',
    'signup.addressContact.streetAddressPlaceholder': 'أدخل عنوان الشارع الكامل بما في ذلك اسم المبنى والطابق ورقم المكتب',
    'signup.addressContact.city': 'المدينة',
    'signup.addressContact.cityPlaceholder': 'أدخل اسم المدينة',
    'signup.addressContact.emirate': 'الإمارة',
    'signup.addressContact.selectEmirate': 'اختر الإمارة',
    'signup.addressContact.country': 'الدولة',
    'signup.addressContact.selectCountry': 'اختر الدولة',
    'signup.addressContact.poBox': 'صندوق بريد',
    'signup.addressContact.poBoxPlaceholder': 'أدخل صندوق البريد (اختياري)',
    'signup.addressContact.poBoxNote': 'اختياري - للمراسلات البريدية',
    'signup.addressContact.contactInformation': 'معلومات الاتصال',
    'signup.addressContact.landline': 'الهاتف الثابت / هاتف بديل',
    'signup.addressContact.landlinePlaceholder': '+971 4 123 4567',
    'signup.addressContact.landlineNote': 'الهاتف الثابت للمكتب أو رقم اتصال بديل',
    'signup.addressContact.socialMediaLinks': 'روابط وسائل التواصل الاجتماعي',
    'signup.addressContact.socialMediaNote': 'أضف روابط ملفاتك الشخصية على وسائل التواصل الاجتماعي (اختياري)',
    'signup.addressContact.facebook': 'فيسبوك',
    'signup.addressContact.facebookPlaceholder': 'https://facebook.com/yourpage',
    'signup.addressContact.twitter': 'إكس (تويتر)',
    'signup.addressContact.twitterPlaceholder': 'https://x.com/yourhandle',
    'signup.addressContact.tiktok': 'تيك توك',
    'signup.addressContact.tiktokPlaceholder': 'https://tiktok.com/@yourhandle',
    'signup.addressContact.instagram': 'إنستغرام',
    'signup.addressContact.instagramPlaceholder': 'https://instagram.com/yourhandle',
    'signup.addressContact.addressVerification': 'التحقق من العنوان',
    'signup.addressContact.addressVerificationNote': 'سيتم استخدام هذا العنوان للمراسلات الرسمية وقد يتم التحقق منه كجزء من عملية الموافقة على الحساب. يرجى التأكد من دقة جميع التفاصيل.',
    'signup.addressContact.emirates.abudhabi': 'أبو ظبي',
    'signup.addressContact.emirates.dubai': 'دبي',
    'signup.addressContact.emirates.sharjah': 'الشارقة',
    'signup.addressContact.emirates.ajman': 'عجمان',
    'signup.addressContact.emirates.uaq': 'أم القيوين',
    'signup.addressContact.emirates.rak': 'رأس الخيمة',
    'signup.addressContact.emirates.fujairah': 'الفجيرة',
    'signup.addressContact.countries.uae': 'دولة الإمارات العربية المتحدة',
    'signup.addressContact.countries.saudi': 'المملكة العربية السعودية',
    'signup.addressContact.countries.qatar': 'قطر',
    'signup.addressContact.countries.kuwait': 'الكويت',
    'signup.addressContact.countries.bahrain': 'البحرين',
    'signup.addressContact.countries.oman': 'عمان',
    
    // Payment Preferences
    'signup.paymentPreferences.optionalStep': 'خطوة اختيارية',
    'signup.paymentPreferences.optionalStepNote': 'يمكن إعداد تفضيلات الدفع الآن أو لاحقاً في إعدادات ملفك الشخصي. يمكنك دائماً تحديث هذه التفاصيل قبل دفع أول حملة لك.',
    'signup.paymentPreferences.preferredPaymentMethod': 'طريقة الدفع المفضلة',
    'signup.paymentPreferences.choosePaymentMethod': 'اختر طريقتك المفضلة لدفع ثمن الحملات',
    'signup.paymentPreferences.creditCard': 'بطاقة ائتمانية/مدينة',
    'signup.paymentPreferences.creditCardDescription': 'ادفع باستخدام فيزا أو ماستركارد أو بطاقات رئيسية أخرى',
    'signup.paymentPreferences.bankTransfer': 'حوالة بنكية',
    'signup.paymentPreferences.bankTransferDescription': 'حوالة بنكية مباشرة (قد تستغرق 1-3 أيام عمل)',
    'signup.paymentPreferences.check': 'دفع بالشيك',
    'signup.paymentPreferences.checkDescription': 'دفع بالشيك التقليدي (وقت معالجة أطول)',
    'signup.paymentPreferences.popular': 'شائع',
    'signup.paymentPreferences.billingContact': 'مسؤول الفواتير',
    'signup.paymentPreferences.billingContactPlaceholder': 'اسم الشخص المسؤول عن أمور الفواتير',
    'signup.paymentPreferences.billingContactNote': 'الشخص المسؤول عن التواصل المتعلق بالمدفوعات',
    'signup.paymentPreferences.vatNumber': 'رقم تسجيل ضريبة القيمة المضافة',
    'signup.paymentPreferences.vatNumberPlaceholder': 'أدخل رقم تسجيل ضريبة القيمة المضافة (إن أمكن)',
    'signup.paymentPreferences.vatNumberNote': 'مطلوب للشركات المسجلة في ضريبة القيمة المضافة. اتركه فارغاً إذا لم ينطبق.',
    'signup.paymentPreferences.paymentSecurity': 'أمان الدفع',
    'signup.paymentPreferences.securityFeature1': 'جميع معلومات الدفع مشفرة ومحفوظة بأمان',
    'signup.paymentPreferences.securityFeature2': 'نحن لا نحفظ تفاصيل البطاقة الائتمانية الكاملة على خوادمنا',
    'signup.paymentPreferences.securityFeature3': 'المدفوعات تتم معالجتها عبر بوابات دفع آمنة معتمدة',
    
    // UserRoleType
    'signup.userRoleType.stepRemoved': 'تم إزالة الخطوة',
    'signup.userRoleType.stepRemovedDescription': 'تم نقل اختيار نوع الحساب إلى الخطوة التالية. يرجى المتابعة.',
    'signup.userRoleType.stepCompleted': 'تم إكمال الخطوة',
    'signup.userRoleType.stepCompletedDescription': 'تم إزالة هذه الخطوة. يرجى المتابعة إلى الخطوة التالية.',
    'signup.userRoleType.accountSetup': 'إعداد الحساب',
    'signup.userRoleType.agencyMessage': 'كوكالة، ستحصل على أدوات إدارة العملاء المتعددين والميزات المتقدمة.',
    'signup.userRoleType.directMessage': 'كمعلن مباشر، ستحصل على تجربة مبسطة تركز على احتياجات عملك.',

    // ComplianceApproval
    'signup.complianceApproval.approvalProcess': 'عملية الموافقة',
    'signup.complianceApproval.approvalProcessDescription': 'سيخضع طلبك لعملية مراجعة شاملة لضمان الجودة والامتثال لمعايير الإعلان.',
    'signup.complianceApproval.reviewTimeline': 'الجدول الزمني لعملية المراجعة',
    'signup.complianceApproval.creativeReview': 'مراجعة الإبداع',
    'signup.complianceApproval.creativeReviewDescription': 'التحقق من إرشادات المحتوى ومعايير الإبداع',
    'signup.complianceApproval.legalCompliance': 'الامتثال القانوني',
    'signup.complianceApproval.legalComplianceDescription': 'فحص امتثال الشروط والمتطلبات التنظيمية',
    'signup.complianceApproval.financialVerification': 'التحقق المالي',
    'signup.complianceApproval.financialVerificationDescription': 'إعداد الدفع وتقييم الائتман',
    'signup.complianceApproval.estimatedTime': 'الوقت المقدر:',
    'signup.complianceApproval.estimatedTime1': '1-2 أيام عمل',
    'signup.complianceApproval.estimatedTime2': '2-3 أيام عمل',
    'signup.complianceApproval.estimatedTime3': '1-2 أيام عمل',
    'signup.complianceApproval.afterApproval': 'ماذا يحدث بعد الموافقة؟',
    'signup.complianceApproval.afterApproval1': 'ستتلقى رسالة تأكيد عبر البريد الإلكتروني مع بيانات تسجيل الدخول',
    'signup.complianceApproval.afterApproval2': 'الوصول إلى لوحة تحكم منصة الإعلان الكاملة',
    'signup.complianceApproval.afterApproval3': 'إمكانية إنشاء وتشغيل الحملات عبر جميع القنوات',
    'signup.complianceApproval.afterApproval4': 'تعيين مدير حساب مخصص (لحسابات الوكالات)',
    'signup.complianceApproval.finalConfirmation': 'التأكيد النهائي',
    'signup.complianceApproval.infoAccurate': 'أؤكد أن جميع المعلومات المقدمة دقيقة وكاملة',
    'signup.complianceApproval.infoAccurateNote': 'تقديم معلومات خاطئة قد يؤدي إلى رفض الحساب أو إنهاؤه',
    'signup.complianceApproval.termsAccepted': 'أوافق على الشروط والأحكام وسياسة الخصوصية',
    'signup.complianceApproval.termsConditions': 'الشروط والأحكام',
    'signup.complianceApproval.privacyPolicy': 'سياسة الخصوصية',
    'signup.complianceApproval.readyToSubmit': 'هل أنت مستعد لتقديم طلبك؟',
    'signup.complianceApproval.readyToSubmitDescription': 'بمجرد التقديم، ستتلقى رسالة تأكيد عبر البريد الإلكتروني ويمكنك تتبع حالة طلبك من خلال بوابة الدعم الخاصة بنا.',
    'signup.complianceApproval.submitForApproval': 'إرسال للموافقة',
    
    // Form Fields
    'form.required': 'مطلوب',
    'form.optional': 'اختياري',
    'form.select': 'اختر...',
    'form.choose': 'اختر',
    'form.search': 'بحث...',
    'form.filter': 'تصفية',
    'form.all': 'الكل',
    'form.none': 'بدون',
    'form.other': 'أخرى',
    'form.yes': 'نعم',
    'form.no': 'لا',
    'form.save': 'حفظ',
    'form.cancel': 'إلغاء',
    'form.continue': 'متابعة',
    'form.finish': 'إنهاء',
    'form.edit': 'تعديل',
    'form.delete': 'حذف',
    'form.confirm': 'تأكيد',
    'form.close': 'إغلاق',
    
    // General UI
    'ui.loading': 'جاري التحميل...',
    'ui.error': 'خطأ',
    'ui.success': 'نجح',
    'ui.warning': 'تحذير',
    'ui.info': 'معلومات',
    'ui.notFound': 'غير موجود',
    'ui.noData': 'لا توجد بيانات متاحة',
    'ui.tryAgain': 'حاول مرة أخرى',
    'ui.refresh': 'تحديث',
    'ui.viewAll': 'عرض الكل',
    'ui.showMore': 'عرض المزيد',
    'ui.showLess': 'عرض أقل',
    'ui.readMore': 'اقرأ المزيد',
    'ui.collapse': 'طي',
    'ui.expand': 'توسيع',
    'ui.download': 'تحميل',
    'ui.upload': 'رفع',
    'ui.preview': 'معاينة',
    'ui.print': 'طباعة',
    'ui.share': 'مشاركة',
    'ui.copy': 'نسخ',
    'ui.cut': 'قص',
    'ui.paste': 'لصق',
    
    // Platform Selection
    'platforms.title': 'اختر منصتك',
    'platforms.subtitle': 'اختر منصة الإعلام التي تناسب أهداف حملتك الإعلانية. كل منصة تقدم مزايا فريدة للوصول إلى جمهورك المستهدف.',
    'platforms.tv.title': 'التلفزيون',
    'platforms.tv.description': 'وصل إلى الملايين من خلال أوقات الذروة والبرامج الشعبية',
    'platforms.radio.title': 'الراديو',
    'platforms.radio.description': 'تواصل مع المتنقلين والجماهير المحلية',
    'platforms.print.title': 'الإعلام المطبوع',
    'platforms.print.description': 'استهدف القراء المهتمين من خلال إعلانات الصحف والمجلات',
    'platforms.social.title': 'وسائل التواصل الاجتماعي',
    'platforms.social.description': 'تفاعل مع الجيل الرقمي عبر جميع المنصات الرئيسية',
    
    // Dashboard Home specific
    'dashboard.stats.activeBookings': 'الحجوزات النشطة',
    'dashboard.upcomingAds': 'الإعلانات القادمة',
    'dashboard.upcomingAds.scheduled': 'مجدولة',
    'dashboard.upcomingAds.noScheduled': 'لا توجد إعلانات مجدولة قادمة',
    'dashboard.pendingApprovals': 'الموافقات المعلقة',
    'dashboard.pendingApprovals.pending': 'معلقة',
    'dashboard.pendingApprovals.allApproved': 'جميع الحملات معتمدة',
    'dashboard.pendingApprovals.submitted': 'مُرسل:',
    'dashboard.paymentsDue': 'المدفوعات المستحقة',
    'dashboard.paymentsDue.overdue': 'متأخرة',
    'dashboard.paymentsDue.due': 'مستحقة:',
    'dashboard.paymentsDue.payNow': 'ادفع الآن',
    'dashboard.paymentsDue.allUpToDate': 'جميع المدفوعات محدّثة',
    'dashboard.quickActions': 'الإجراءات السريعة',
    'dashboard.quickActions.newBooking': 'حجز جديد',
    'dashboard.quickActions.viewSchedule': 'عرض الجدول',
    'dashboard.quickActions.analytics': 'التحليلات',
    'dashboard.quickActions.billing': 'الفواتير',
    'dashboard.createNewBooking': 'إنشاء حجز جديد',
    'dashboard.backToDashboard': 'العودة إلى لوحة التحكم',
    
    // Review Confirmation
    'review.title': 'مراجعة وتأكيد',
    'review.subtitle': 'يرجى مراجعة تفاصيل حجزك قبل الإرسال',
    'review.step': 'الخطوة 5 من 6',
    'review.back': 'رجوع',
    'review.bookingSummary': 'ملخص الحجز',
    'review.edit': 'تعديل',
    'review.programSchedule': 'البرنامج والجدولة',
    'review.program': 'البرنامج',
    'review.category': 'الفئة',
    'review.date': 'التاريخ',
    'review.timeSlot': 'الفترة الزمنية',
    'review.pricingBreakdown': 'تفصيل الأسعار',
    'review.basePrice': 'السعر الأساسي',
    'review.addOns': 'الإضافات:',
    'review.totalAmount': 'المبلغ الإجمالي',
    'review.adMaterial': 'مواد الإعلان',
    'review.uploadedFile': 'ملف مرفوع',
    'review.yourUploadedAd': 'إعلانك المرفوع',
    'review.readyForReview': 'جاهز للمراجعة',
    'review.customTemplateDesign': 'تصميم قالب مخصص',
    'review.company': 'الشركة',
    'review.message': 'الرسالة',
    'review.toBeCreated': 'سيتم إنشاؤه',
    'review.importantInfo': 'معلومات مهمة',
    'review.reviewTime': '• ستتم مراجعة حجزك خلال 24-48 ساعة',
    'review.paymentProcess': '• ستتم معالجة الدفع بعد الموافقة',
    'review.changesFees': '• التغييرات على الحجوزات المعتمدة قد تتطلب رسوماً إضافية',
    'review.cancellation': '• يجب إلغاء الحجوزات قبل 72 ساعة على الأقل',
    'review.termsConditions': 'الشروط والأحكام',
    'review.agreeToTerms': 'أوافق على',
    'review.termsOfService': 'شروط الخدمة',
    'review.and': 'و',
    'review.adPolicy': 'سياسة الإعلان لشركة Media Intelligence',
    'review.marketingConsent': 'أوافق على تلقي اتصالات تسويقية وتحديثات الحجز عبر البريد الإلكتروني والرسائل النصية',
    'review.keyTerms': 'ملخص الشروط الأساسية:',
    'review.bookingApproval': '• تأكيد الحجز مشروط بالموافقة الإبداعية والقانونية',
    'review.paymentDue': '• الدفع مستحق خلال 7 أيام من الموافقة',
    'review.contentCompliance': '• يجب أن يتوافق المحتوى مع لوائح الإعلام في دولة الإمارات',
    'review.contentRejection': '• تحتفظ MI بالحق في رفض المحتوى غير المناسب',
    'review.refundPolicy': '• المبالغ المستردة متاحة فقط للحجوزات الملغاة من قبل MI',
    'review.backToEdit': 'العودة للتعديل',
    'review.submitForApproval': 'إرسال للموافقة',
    'review.acceptTermsRequired': 'يرجى قبول الشروط والأحكام للمتابعة',
    'review.channel': 'قناة',
    
    // Approval Workflow
    'approval.title': 'سير عمل الموافقة',
    'approval.subtitle': 'تتبع تقدم موافقة حجزك',
    'approval.refresh': 'تحديث',
    'approval.reference': 'المرجع',
    'approval.progressTitle': 'تقدم الموافقة',
    'approval.progressComplete': '% مكتمل',
    'approval.fullyApproved': 'تم اعتماد حجزك وجدولته بالكامل!',
    'approval.currentlyIn': 'حالياً في مرحلة',
    'approval.statusTimeline': 'الجدول الزمني للحالة',
    'approval.reviewFeedback': 'ملاحظات المراجعة',
    'approval.bookingDetails': 'تفاصيل الحجز',
    'approval.mediaOutlet': 'المنفذ الإعلامي',
    'approval.program': 'البرنامج',
    'approval.scheduledDate': 'التاريخ المجدول',
    'approval.totalAmount': 'المبلغ الإجمالي',
    'approval.recentUpdates': 'التحديثات الأخيرة',
    'approval.actions': 'الإجراءات',
    'approval.downloadReceipt': 'تحميل الإيصال',
    'approval.contactSupport': 'الاتصال بالدعم',
    'approval.viewConfirmation': 'عرض التأكيد',
    'approval.needHelp': 'تحتاج مساعدة؟',
    'approval.helpDescription': 'إذا كان لديك أسئلة حول عملية الموافقة، فريق الدعم هنا للمساعدة.',
    'approval.contactSupportLink': 'الاتصال بالدعم ←',
    'approval.currentlyProcessing': 'قيد المعالجة حالياً...',
    'approval.completed': 'تم الانتهاء',
    'approval.eta': 'الوقت المتوقع',
    
    // Approval Stages
    'stages.submitted.name': 'تم الإرسال',
    'stages.submitted.desc': 'تم استلام الحجز وإدراجه في قائمة الانتظار للمراجعة',
    'stages.creativeReview.name': 'المراجعة الإبداعية',
    'stages.creativeReview.desc': 'فريق الإبداع يراجع محتوى الإعلان',
    'stages.legalReview.name': 'المراجعة القانونية',
    'stages.legalReview.desc': 'الامتثال القانوني والتحقق من المحتوى',
    'stages.approved.name': 'تمت الموافقة',
    'stages.approved.desc': 'تم إكمال جميع الموافقات، جاهز للجدولة',
    'stages.scheduled.name': 'تم الجدولة',
    'stages.scheduled.desc': 'تم تأكيد الإعلان وجدولته للبث',
    
    // Status Labels
    'status.completed': 'مكتمل',
    'status.inProgress': 'قيد التنفيذ',
    
    // Feedback Messages
    'feedback.creative': 'نجحت المراجعة الإبداعية. المحتوى يلبي معايير البث.',
    'feedback.legal': 'اكتملت المراجعة القانونية. المحتوى يتوافق مع لوائح الإعلام في دولة الإمارات.',
    'feedback.creativeTitle': 'المراجعة الإبداعية',
    'feedback.legalTitle': 'المراجعة القانونية',
    
    // Notifications
    'notifications.creativeStarted.title': 'بدأت المراجعة الإبداعية',
    'notifications.creativeStarted.message': 'يتم الآن مراجعة إعلانك من قبل فريقنا الإبداعي.',
    'notifications.paymentConfirmed.title': 'تم تأكيد الدفع',
    'notifications.paymentConfirmed.message': 'تم معالجة دفعتك بقيمة {amount} درهم إماراتي بنجاح.',
    'notifications.bookingSubmitted.title': 'تم إرسال الحجز',
    'notifications.bookingSubmitted.message': 'تم إرسال حجزك وتعيين رقم المرجع {bookingId}',
    'notifications.hoursAgo': 'منذ {hours} ساعات',
    'notifications.hourAgo': 'منذ ساعة واحدة'
  }
};

interface LanguageContextType {
  language: Language;
  isRTL: boolean;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: TranslationParameters) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar'); // Default to Arabic

  const isRTL = language === 'ar';

  const t = (key: string, params?: TranslationParameters): string => {
    const translation = (translations[language] as any)[key] || key;
    
    if (params) {
      return Object.entries(params).reduce((text, [paramKey, paramValue]) => {
        return text.replace(`{{${paramKey}}}`, String(paramValue));
      }, translation);
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, isRTL, setLanguage, t }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className="w-full">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};